### ISSUE TITLE
Write tutorial NB for research

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#100]

**Comment by gusgordon** [comment]
I think the general format should be similar to the zipline one. Maybe the full tear sheet at the bottom instead so it doesn't take up a massive chunk of space.

We probably want to urge users to use the backtest.full_tear_sheet() or whatever etc. format, but also advertise that they can explicitly call pf.make_full_tear_sheet(). This could be kind of confusing but is probably the best way. You guys have any thoughts?

**Comment by twiecki** [comment]
yeah, that sounds like a good plan. I think we should just supply an algo_id that will work for everyone (like the example NB does for get_backtest()). Then we start with the very simple `backtest.full_tear_sheet()` as you said and list the other methods that exist with short descriptions. Then we can say that this is implemented via pyfolio which is now also available with some simple examples. I agree that it shouldn't be too long. Once people know where to look they will probably figure it out.

**Comment by gusgordon** [comment]
Also we need to write a forum post. I suppose I can post an example with a zipline algo and go into some extra detail about some of the tear sheets, then tell people they have another example in their tutorial directory on research.

**Comment by twiecki** [comment]
@gusgordon Do you have access to the staging server with the research pyfolio API? We can probably draft something up there and then move it over.

**Comment by gusgordon** [comment]
Yeah, sure. I'll do this tomorrow if I can get a good connection and share it with you guys for feedback after.

**Comment by gusgordon** [comment]
Sorry, internet has been pretty shoddy and I can't get a consistent whitelist. Trying to do this ASAP.

**Comment by twiecki** [comment]
@gusgordon I'll take a stab at this and will run what I have by you.
