### ISSUE TITLE
Sometimes transaction plot breaks

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#101]
![image](https://cloud.githubusercontent.com/assets/674200/9008366/2adad7b0-379a-11e5-9f9e-c445b0072e74.png)
Not sure when this occurs, might be a data issue but I wanted to keep track of it.

**Comment by humdings** [comment]
I have a hunch this is a bug in the users algo. My guess is they have something along these lines in their code that causes the algo to go dark.
```
if get_open_orders():
    return
```
