### ISSUE TITLE
Investigate default figure sizes

### ISSUE THREAD

**Issue by gusgordon** [quantopian/pyfolio#103]
@ACampbell22 was using pyfolio and generating plots for use outside of NBs. For him, there was some extra space at the top and bottom of the returns figure, and likely others. Theory is that IPython is automatically trimming the figure where there wasn't a plot in the area, but could be something else.

**Comment by twiecki** [comment]
@ACampbell22 It's a bit hard to reproduce without any other pointers. Have you resolved this?

**Comment by twiecki** [comment]
@ACampbell22 is this still an issue? feel free to reopen if yes.
