### ISSUE TITLE
create_returns_tearsheet timezone issue

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#105]
Still some timezone issues in create_returns_tearsheet. See attached screenshot.  The 2nd screenshot shows that the timeseries I'm trying to build a tearsheet for has UTC specified as its tz

![image](https://cloud.githubusercontent.com/assets/6541022/9051081/96c13362-3a0a-11e5-93ea-85543e01a38b.png)

![image](https://cloud.githubusercontent.com/assets/6541022/9051097/bb9d752e-3a0a-11e5-921b-b76509043558.png)

**Comment by humdings** [comment]
Can you try that with `live_start_date=pd.Timestamp('2015-01-01', tz='utc')` and see if that's what is causing it. We might have to timezoneify that date as well.

**Comment by justinlent** [comment]
yep @humdings that gets it working! I guess we should stamp live_start_date with a 'utc' tz if it gets passed in without a tz?

**Comment by humdings** [comment]
Ya, that should do it, I'll do that now, should be easy enough.

**Comment by humdings** [comment]
This should be fixed once https://github.com/quantopian/pyfolio/pull/106 is merged

**Comment by twiecki** [comment]
Fixed with #106.
