### ISSUE TITLE
formatting fix: remove timestamps from peak/valley dates in drawdown table

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#107]
![image](https://cloud.githubusercontent.com/assets/6541022/9052737/faf19ef2-3a1f-11e5-8ea6-cfc0ccda9274.png)

**Comment by justinlent** [comment]
Even though this is just a formatting thing, we really should fix it as it will allow the entire dataframe to be printed without overflowing.  For the non-technical folks, seeing the minutes/seconds timestamps is also likely very confusing

**Comment by twiecki** [comment]
+1

**Comment by gusgordon** [comment]
I can tackle this too, I was also trying to think about ways we could reformat all the text at the beginning to look a bit nicer.

**Comment by twiecki** [comment]
Appreciate it @gusgordon.
