### ISSUE TITLE
Store SPY in csv instead?

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#111]
Although hdf5 is certainly the better format it's an additional requirement. For this simple file we might want to just use `csv` instead.

**Comment by humdings** [comment]
Pandas doesn't support hdf5 natively? What's the additional requirement?

**Comment by twiecki** [comment]
`pytables`

**Comment by gusgordon** [comment]
We could also store in a zip, the file sizes may get large

**Comment by twiecki** [comment]
I'm not overly worried about that since it's only one ticker. I just remembered that we also have the fama french stuff in hdf5. That one might be a bit larger. Anyway, if size is indeed a concern we should probably stick to hdf5 and eat the dependency.

**Comment by twiecki** [comment]
Seems like csv is actually smaller, at least for the fama french factors.
```
-rw-rw-r-- 1 wiecki wiecki 1.4M Aug 14 11:00 factors.csv
-rw-rw-r-- 1 wiecki wiecki 2.3M Aug 14 10:20 factors.h5
-rw-rw-r-- 1 wiecki wiecki 264K Aug 14 10:43 spy.csv
-rw-rw-r-- 1 wiecki wiecki 138K Aug 14 10:20 spy.h5
```

**Comment by twiecki** [comment]
https://github.com/quantopian/pyfolio/pull/119

**Comment by twiecki** [comment]
Closed with https://github.com/quantopian/pyfolio/pull/119.
