### ISSUE TITLE
Should be able to pass in a string for live_start_date

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#114]
this use to work, then broke when improving the timezone stuff
Basically any valid/parsable time string should be valid.  any string that 'just works' when passed to pd.Timestamp() is probably a reasonable bar

![image](https://cloud.githubusercontent.com/assets/6541022/9090351/99f94660-3b4e-11e5-9c43-17a7ba3d626e.png)

**Comment by twiecki** [comment]
Definitely.
