### ISSUE TITLE
Show '% of portfolio' traded instead of shares traded for turnover plots

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#124]
where (% of portfolio) = ($ traded) / (portfolio value),

and,  ($ traded) = (stock price) * (# of shares)

![image](https://cloud.githubusercontent.com/assets/6541022/9371101/bd32189a-468a-11e5-8bde-d08a56c6b46f.png)

**Comment by twiecki** [comment]
+1

**Comment by humdings** [comment]
I think this is a pretty quick change, I agree that volume plots are pretty uninformative. 

The `plot_turnover` function is already plotted as a percentage of portfolio value, except it's 
`0.5*($ traded) / (portfolio value)`.

Maybe we can remove the volume plot from the tear sheet and replace the volume histogram with a histogram of the daily turnover rates. The turnover histogram would be a more informative plot.

**Comment by twiecki** [comment]
+1

**Comment by twiecki** [comment]
Closed with https://github.com/quantopian/pyfolio/pull/133. Thanks @humdings!
