### ISSUE TITLE
Live trend appears to be broken in plot_rolling_returns()

### ISSUE THREAD

**Issue by MatthewGilbert** [quantopian/pyfolio#128]
In the cumulative returns plot the live trend appears to just be the same as the backtest trend? I have included some code and a screenshot below to illustrate the problem.

    import pyfolio as pf
    import matplotlib.pyplot as plt
    import matplotlib.gridspec as gridspec
    stock_rets_SPY = pf.utils.get_symbol_rets('SPY')
    stock_rets_QQQ = pf.utils.get_symbol_rets('QQQ')
    stock_rets_GLD = pf.utils.get_symbol_rets('GLD')
    stock_rets_TLT = pf.utils.get_symbol_rets('TLT')
    portfolio_4_assets_rets = pf.timeseries.portfolio_returns([stock_rets_SPY, -1 * stock_rets_QQQ,   stock_rets_GLD, stock_rets_TLT], exclude_non_overlapping=True)
    portfolio_4_assets_rets.iloc[-150:-1] = -.001
    benchmark_rets = pf.utils.get_symbol_rets('SPY')
    vertical_sections = 10 
    fig = plt.figure(figsize=(14, vertical_sections * 6))
    gs = gridspec.GridSpec(vertical_sections, 3, wspace=0.5, hspace=0.5)
    ax_rolling_returns = plt.subplot(gs[:2, :])
    pf.plotting.plot_rolling_returns(
        portfolio_4_assets_rets,
        benchmark_rets=benchmark_rets,
        live_start_date='2013-10-22',
        cone_std=1,
        ax=ax_rolling_returns)

![selection_016](https://cloud.githubusercontent.com/assets/2401026/9455861/bf77f612-4a9d-11e5-95d0-9762ab52242b.png)

This looks like it is being caused by timeseries.cone_rolling(). Is this the intended behaviour or should the timeseries cone be refit to the out of sample data?

**Comment by gusgordon** [comment]
You're right — thanks.

**Comment by MatthewGilbert** [comment]
Also this is sort of pedantic but it might make sense to have the cumulative returns start from 0 not 1. 1 would be more appropriate if this was something like notional/capital but on day 0 your strategies cumulative returns are 0 not 100%

**Comment by twiecki** [comment]
@MatthewGilbert Thanks for commenting. I think this is intentional. The assumption you want to test is if the out-of-sample (OOS) behaves like the backtest predicted. Thus you assume that the linear trend will continue. Then if the OOS moves outside of the cone you have reason to believe that something went wrong.

Agreed on starting at 0.

**Comment by MatthewGilbert** [comment]
Ahh okay, makes sense. I was just a bit unclear on it's intended functionality. "Live trend" might be a bit of a misnomer, although I can't really think of a concise description of that.

**Comment by twiecki** [comment]
@MatthewGilbert good point. Maybe 'predicted trend' ?

**Comment by MatthewGilbert** [comment]
Ya that seems more appropriate.

**Comment by gusgordon** [comment]
Ah, right, the cone gets projected around the in-sample regression. My mistake.

**Comment by justinlent** [comment]
Hi Matthew, Thanks for all the great feedback - very much appreciated.  wrt the "cumulative performance" plot starting at 1.0: it's really meant to be interpretated as $1 being invested in Day 1; this is synonymous with Fund Summary sheets that often show $10,000 invested in Day 1 turns into $X down the road... I can see us exposing a toggle though to start at 0.0 instead

**Sent from iPhone**




On Mon, Aug 24, 2015 at 7:09 PM -0700, "Matthew Gilbert" <notifications@github.com> wrote:












Also this is sort of pedantic but it might make sense to have the cumulative returns start from 0 not 1. 1 would be more appropriate if this was something like notional/capital but on day 0 your strategies cumulative returns are 0 not 100%

**Comment by MatthewGilbert** [comment]
@justinlent I think having the plot in capital terms is reasonable but it's a bit confusing since the axis reads "Cumulative returns" as opposed to something like "Dollars Invested", "Notional" or "Capital". Again this is fairly pedantic hence why I just tacked it on to my main concern so if there is a bias to leave it as is I think that is fine.
