### ISSUE TITLE
Pyfolio tries to cache data inside the package which is not always writable

### ISSUE THREAD

**Issue by adzuci** [quantopian/pyfolio#129]
Related to https://github.com/quantopian/pyfolio/issues/125

@CaptainKanuk found that if pyfolio doesn't have access to write to it's directory certain functions are broken.

![screen shot 2015-08-25 at 6 36 36 pm](https://cloud.githubusercontent.com/assets/278814/9481462/8156cb7c-4b58-11e5-8a80-d7164b6c9a8c.png)

`plot_rolling_risk_factors()` won't work in this case unless we have pyfolio cache data in somewhere like `~/.pyfolio` which follows a similar pattern to `~/.zipline`

**Comment by adzuci** [comment]
I think the change to https://github.com/quantopian/pyfolio/blob/master/pyfolio/utils.py#L51 should be something like:

`return join(expanduser("~"), '.zipline', 'data', name)`

after adding `expanduser` after line 21.

**Comment by twiecki** [comment]
Ping @llllllllll. @richafrank said you could help with this.

**Comment by twiecki** [comment]
Closed with #241.
