### ISSUE TITLE
ipynb in docs/notebooks is Symbolic Link.

### ISSUE THREAD

**Issue by cedricporter** [quantopian/pyfolio#132]
https://github.com/quantopian/pyfolio/blob/master/docs%2Fnotebooks%2Fsingle_stock_example.ipynb

This is a Symbolic Link. I can NOT open it.

**Comment by twiecki** [comment]
@cedricporter this is intentional. Did anything link there? If you follow the symlink, here is where the file is located: https://github.com/quantopian/pyfolio/blob/master/pyfolio/examples/single_stock_example.ipynb

**Comment by cedricporter** [comment]
Oh, I see.
