### ISSUE TITLE
Plot of Equity Curve normalized by Gross Leverage timeseries

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#143]
This would provide a hypothetical view of how an algo would peform if the algo implemented order logic such that it was always invested at 1.0 leverage every day

The Gross Leverage timeseries is available in the zipline daily perf packet I believe

**Comment by justinlent** [comment]
I just realized this is more difficult than anticipated unless the gross leverage normalization is done at the minutely level.  Case being is that the zipline daily perf packet gross leverage timeseries is simply the gross leverage at the end of the day, which might be a really small value even if the portfolio had a really high leverage during the day and created a lot of profit. So you wouldn't want to normalize using this really small end-of-day gross leverage value and unrealistically inflate the profits by a large factor

**Comment by twiecki** [comment]
I think we do that now.
