### ISSUE TITLE
Change Positions Level Exposure plot to track Gross Leverage plot

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#144]
@humdings It looks like we will want to update the Ticker/Positions Level Exposure plot to track Gross Leverage in the same way which you updated the Long/Short Exposure plot per this PR:  https://github.com/quantopian/pyfolio/pull/140

How easy/difficult do you think it would be to update the Ticker/Positions Level Exposure plot in a similar fashion?

**Comment by humdings** [comment]
@justinlent Where would I update this functionality? Is it just making `pos.get_portfolio_alloc` drop the cash as well? This will also need to work for both daily and intraday data I'm guessing.

**Comment by justinlent** [comment]
@humdings David, yep, I think it's as simple to drop the cash as well.  Since we don't really support any intraday analysis (yet) in pyfolio, I think its safe to just get it working at daily frequency for now

**Comment by georgh0021** [comment]
Looks like #147 resolved this!
