### ISSUE TITLE
add table for top 10/bottom 10 winners/losers 

### ISSUE THREAD

**Issue by Jstauth** [quantopian/pyfolio#15]
Table: Top and Bottom 10 holdings by contribution to performance ever, and per year (long, short, overall) - performance is over the time position was held in portfolio.

Performance, weight and relative contribution for top 10 holdings, ranked from largest contribution to smallest

"best" and "worst" positions basically

**Comment by georgh0021** [comment]
2 years down the line and pyfolio now has this functionality 😄  Closing this issue now.
