### ISSUE TITLE
Use pandas-datareader instead of deprecated pandas.io

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#151]
https://github.com/pydata/pandas-datareader/ is the new package for loading yahoo finance. they also have fama french loaders.

**Comment by jonathanng** [comment]
+1

**Comment by twiecki** [comment]
Closed with https://github.com/quantopian/pyfolio/commit/7589050d7dc8df44a89c6e72e96d24b2ca237d82.
