### ISSUE TITLE
Linear cone broken in volatility matched cumulative returns plot

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#152]
We seem to compute the cone on the non-volatility-matched returns.
![image](https://cloud.githubusercontent.com/assets/674200/10123130/54fcbab8-6530-11e5-830c-75d4ddd77bc5.png)

**Comment by justinlent** [comment]
I propose we just remove the cone on this volatility matched plot. While working on the new multi-shaded cone branch I see how to fix this pretty easily, so I'll take it

**Comment by twiecki** [comment]
+1 on removing the cone for the vol-matched case.

**Comment by twiecki** [comment]
Fixed by https://github.com/quantopian/pyfolio/pull/168
