### ISSUE TITLE
BUG Fama-French factors fail to load because source data format has changed

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#157]
For the "UMD" (Momentum) factor, the source data column seems to have changed its name from "UMD" to "Mom"

![image](https://cloud.githubusercontent.com/assets/6541022/10168031/c0e8d676-667f-11e5-98c0-293b60f8703f.png)

**Comment by twiecki** [comment]
Actually this might already be fixed in master.

**Comment by justinlent** [comment]
Closing this for now. It looks to be fixed
