### ISSUE TITLE
add traditional single factor betas 

### ISSUE THREAD

**Issue by Jstauth** [quantopian/pyfolio#16]
first off we need to define which sids we want to use to proxy these - i think i said I'd do that, but if @justinlent wants to weigh in please do!

Traditional single factor betas: Equity, Bonds, Credit, Gold, Crude Oil, Volatility

**Comment by justinlent** [comment]
Upping to high-priority.  I'll put my existing work on this, as well as the sector risk factors betas on a branch for someone to work from and productize

**Comment by georgh0021** [comment]
Looks like #391 addresses the issue of the risk factor betas, and #25 also expresses a similar need. Closing this issue now.
