### ISSUE TITLE
Change cone shading to show 1.0, 1.5, 2.0 stdev regions

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#167]

**Comment by justinlent** [comment]
@twiecki Can you look at my PR for this and see if you can figure out why Travis is failing? I fixed some obvious PEP8 and Python3 compat issues but now it looks like some weird ipython issues are cropping up but I did not even commit any new notebooks in this PR, so I'm stumped.

https://github.com/quantopian/pyfolio/pull/168

**Comment by twiecki** [comment]
I'm investigating, but yeah, pretty sure it's unrelated to your changes.

**Comment by twiecki** [comment]
Closing in favor of #168.
