### ISSUE TITLE
add sector exposure/ sector breakout analysis

### ISSUE THREAD

**Issue by Jstauth** [quantopian/pyfolio#17]
need to find a way to link up MS asset classifications, or some other external data source to do this one.

Sectors (10-GIC levels to start, or whatever similar we have from Morningstar)
Table: Per year and overall sector weight longs, shorts, net, absolute and relative performance of each 
Plot (timeseries): portfolio weight in each sector over time

**Comment by twiecki** [comment]
Implemented by https://github.com/quantopian/pyfolio/pull/166.
