### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by cgdeboer** [quantopian/pyfolio#171]
Perhaps after pull requests (particularly from the outside), like https://github.com/quantopian/pyfolio/pull/164, we could bump the version up to 0.1.1 (or some microversion-ish thing) and submit to pypi (which I imagine would happen after the build issue is resolved). 

This would help immensely in cases (like mine ;) ) where pyfolio is a requirement in a project, and in order for pip to reinstall pyfolio  in my project, a version bump bump is required.

I hope that ramble made some sense...

**Comment by twiecki** [comment]
Yeah, `0.2` is overdue. We can do that tomorrow.

**Comment by cgdeboer** [comment]
Thanks @twiecki !!!
