### ISSUE TITLE
pf.create_returns_tear_sheet(stock_rets) gives KeyError

### ISSUE THREAD

**Issue by cmorgan** [quantopian/pyfolio#176]
running pyfolio/examples/single_stock_example.ipynb gives

KeyError: ("None of [DatetimeIndex(['2012-05-21', '2012-05-22', '2012-05-23', '2012-05-24',\n               '2012-05-25', '2012-05-29', '2012-05-30', '2012-05-31',\n               '2012-06-01', '2012-06-04',\n               ...\n
            '2012-11-07', '2012-11-08', '2012-11-09', '2012-11-12',\n               '2012-11-13', '2012-11-14', '2012-11-15', '2012-11-16',\n               '2012-11-19', '2012-11-20'],\n              dtype='datetime64[ns, UTC]', name=u'Date', length=127, freq=None)] are in the [index]", u'occurred at index SMB')

last line of pyfolio code executed is:
--> 726     beta, alpha = sp.stats.linregress(factor_returns.loc[ret_index].values,
    727                                       returns.values)[:2]

is this a known issue?

**Comment by twiecki** [comment]
Are you using pandas 0.17?

**Comment by cmorgan** [comment]
That was it, also some libraries want to install the most recent numpy so had to fix the numpy installed version.

What are this projects thoughts on conda for dependency management?

The output of ``conda env export`` with pyfolio installed as ``python setup.py develop``:

dependencies:
- certifi=14.05.14=py27_0
- decorator=4.0.4=py27_0
- funcsigs=0.4=py27_0
- ipykernel=4.1.0=py27_0
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.0.3=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_0
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.4.3=np19py27_10
- mistune=0.7.1=py27_0
- mock=1.3.0=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- nose=1.3.7=py27_0
- notebook=4.0.6=py27_0
- numpy=1.9.3=py27_0
- pandas=0.16.2=np19py27_0
- path.py=8.1.2=py27_0
- patsy=0.4.0=np19py27_0
- pbr=1.3.0=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.0=py27_1
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.10.4=py27_1
- pyreadline=2.1=py27_0
- python=2.7.10=1
- python-dateutil=2.4.2=py27_0
- pytz=2015.6=py27_0
- pyzmq=14.7.0=py27_0
- qtconsole=4.1.0=py27_0
- scikit-learn=0.16.1=np19py27_0
- scipy=0.16.0=np19py27_0
- seaborn=0.6.0=np19py27_0
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- six=1.10.0=py27_0
- ssl_match_hostname=3.4.0.2=py27_0
- statsmodels=0.6.1=np19py27_0
- tornado=4.2.1=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1

**Comment by twiecki** [comment]
We just added a bunch of fixes for pandas 0.17 so if you try master it should work with numpy 0.10 and pandas 0.17. I'm using anaconda fine with pyfolio.

**Comment by jkrauss82** [comment]
Hi there

I am on Mac OSX 10.9.5, python 2.7, pandas 0.17.0, numpy 1.10.1 and ran into the same problem:

`File "/Library/Python/2.7/site-packages/pandas/core/indexing.py", line 1280, in _has_valid_type
    (key, self.obj._get_axis_name(axis)))
KeyError: ("None of [DatetimeIndex(['2014-03-28', '2014-03-31', '2014-04-01', '2014-04-02',\n               '2014-04-03', '2014-04-04', '2014-04-07', '2014-04-08',\n               '2014-04-09', '2014-04-10',\n               ...\n               '2014-09-15', '2014-09-16', '2014-09-17', '2014-09-18',\n               '2014-09-19', '2014-09-22', '2014-09-23', '2014-09-24',\n               '2014-09-25', '2014-09-26'],\n              dtype='datetime64[ns, UTC]', name=u'Date', length=127, freq=None)] are in the [index]", u'occurred at index SMB')`

I tried other combinations of numpy and pandas versions, non would work.

Any ideas?

**Comment by twiecki** [comment]
Will take a look soon.

**Comment by jkrauss82** [comment]
Short update: I cloned pyfolio from github and tried again with that version. Works fine now, so I guess whatever caused the error before has been fixed in the meantime. Before I used pyfolio in the version currently available through pip.

**Comment by twiecki** [comment]
Ah, right. i bet https://github.com/quantopian/pyfolio/commit/709553a55b5df7c908d17f443cb17b51854a65be fixed it. Maybe we should release 0.3.1 soon.
