### ISSUE TITLE
Display OOS data in box plot

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#183]
This plot:
![image](https://cloud.githubusercontent.com/assets/674200/15658222/11c2a450-26ba-11e6-8445-2903c98eefb0.png)

Should have the OOS daily, monthly and quarterly returns (if provided) as red crosses overlaid.

**Comment by ahgnaw** [comment]
@twiecki Should the boxplots (not the overlaid red crosses) include OOS data?

**Comment by ahgnaw** [comment]
@twiecki I can overlay a stripplot of the oos data, however neither "x" or "+" are available marker styles. Here are three alternatives:

Default
![image](https://cloud.githubusercontent.com/assets/921335/15757236/9e138dce-28d2-11e6-88b3-a2c3542240de.png)

"."
![image](https://cloud.githubusercontent.com/assets/921335/15757341/1d81baa4-28d3-11e6-89e9-14880c21d721.png)

"d"
![image](https://cloud.githubusercontent.com/assets/921335/15757528/f064021a-28d3-11e6-958b-03246ce1a900.png)


Do you have a preference? The second one looks the cleanest.

**Comment by twiecki** [comment]
Very cool!

> Should the boxplots (not the overlaid red crosses) include OOS data?

No they should not.

I like the 3rd one as it pops out but is still kinda clean.

**Comment by twiecki** [comment]
Closed by https://github.com/quantopian/pyfolio/pull/306#issuecomment-224080196

**Comment by ahgnaw** [comment]
https://github.com/quantopian/pyfolio/pull/306

**Comment by ahgnaw** [comment]
https://github.com/quantopian/pyfolio/pull/308
