### ISSUE TITLE
Transaction parsing broken

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#185]
might be because I had to downgrade to pandas 0.16.1 in order to get zipline working for me.

![image](https://cloud.githubusercontent.com/assets/6541022/10823960/5a696218-7e1b-11e5-921f-95995d05a12c.png)

**Comment by danbob123** [comment]
+1

**Comment by twiecki** [comment]
@justinlent Is this still occurring?

**Comment by justinlent** [comment]
I think this is fixed with the latest commits on master, so I'll close it. We can re-open later if needed
