### ISSUE TITLE
Remove hard-coded "S&P500"

### ISSUE THREAD

**Issue by jkrauss82** [quantopian/pyfolio#191]
if providing individual benchmark_rets (e. g. ^GDAXI) some plots still show S&P500 in headline

Affected functions in plotting.py:
plot_rolling_beta
plot_rolling_returns

**Comment by twiecki** [comment]
Thanks @jkrauss82. Want to submit a PR that fixed it?

**Comment by twiecki** [comment]
Fixed by #192.
