### ISSUE TITLE
bayesian fail to plot if my testing period is too long?

### ISSUE THREAD

**Issue by leoleolam** [quantopian/pyfolio#198]
i was using plot_bayes_cone(rets, live_start_date = pd.Timestamp('2011-11-04', tz='UTC')) 
if i move the live_start_date to a later date say 2013-11-04 it works fine. However, if i move it earlier it fail. 
I also use a longer training series, it fails too
not much clue even I know where it is failing. 

Is it a known issue? like we cannot put our live_start_date too earlier...
would need some advise
```
fail in
in _plot_bayes_cone(returns_train, returns_test, preds, plot_train_len, ax)
    510     print returns_train_cum
    511 
--> 512     returns_train_cum.plot(ax=ax, color='g', label='in-sample')
    513     returns_test_cum_rel.plot(ax=ax, color='r', label='out-of-sample')
    514 
........

ticker.pyc in bin_boundaries(self, vmin, vmax)
   1345                 break
   1346         if self._trim:
-> 1347             extra_bins = int(divmod((best_vmax - vmax), step)[0])
   1348             nbins -= extra_bins
   1349         return (np.arange(nbins + 1) * step + best_vmin + offset)

ValueError: cannot convert float NaN to integer 

```

**Comment by twiecki** [comment]
Seems more like you have nans in the returns. Can you call after `.dropna()` on your inputs?

**Comment by twiecki** [comment]
@leoleolam ping

**Comment by leoleolam** [comment]
Hi twiecki,

I am now using an example which getting price from load_from_yahoo. And then I compute returns with dropna, it still getting the same issue. Would you be able to replicate and advise?

from zipline.utils.factory import load_from_yahoo

start = datetime(2001, 1, 1, 0, 0, 0, 0, pytz.utc)
end = datetime(2015, 1, 1, 0, 0, 0, 0, pytz.utc)
        # Load price data from yahoo.
data = load_from_yahoo(stocks=['CL'], indexes={}, start=start,
                                end=end)

rets = (data/data.shift(1) -1)

rets =  rets['CL'].dropna()

pf.create_bayesian_tear_sheet(rets['CL'], live_start_date = pd.Timestamp('2011-11-04', tz='UTC'))

Thanks.

**Comment by leoleolam** [comment]
@twiecki 

sorry, last line should be 
pf.create_bayesian_tear_sheet(rets, live_start_date = pd.Timestamp('2011-11-04', tz='UTC'))

**Comment by twiecki** [comment]
I was able to run this:
```

CL
Running T model
 [-----------------100%-----------------] 2000 of 2000 complete in 5.5 sec
Finished T model (required 51.05 seconds).

Running BEST model
 [-----------------100%-----------------] 2000 of 2000 complete in 8.1 sec
Finished BEST model (required 55.14 seconds).

Finished plotting Bayesian cone (required 0.92 seconds).

Finished plotting BEST results (required 1.69 seconds).

Finished computing Bayesian predictions (required 0.18 seconds).

Finished plotting Bayesian VaRs estimate (required 0.09 seconds).

Running alpha beta model
 [-----------------100%-----------------] 2000 of 2000 complete in 6.6 sec
Finished running alpha beta model (required 34.82 seconds).

Finished plotting alpha beta model (required 0.31 seconds).

Total runtime was 144.20 seconds.
```

![figure_1](https://cloud.githubusercontent.com/assets/674200/11209108/6c44f390-8d1f-11e5-9d1c-881057ec1b47.png)

The reason this didn't work for you is probably a recent fix I did here: https://github.com/quantopian/pyfolio/commit/7685f6fdc79253de83349de30ce5d5ff227775e3. So can you retry after updating to pymc3 master and pyfolio master?

I'm closing for now but feel free to reopen if the update doesn't fix your problem.
