### ISSUE TITLE
For convenience, expose returns_style keyword parameter to tearsheet functions

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#207]
Lot's of people have personal opinions as to the style they want to use for computing annual returns.  Allow them to easily specify this such that it flows through to all the functions reliant on an annual returns computation.  

For example, by default we are doing "compound" (Which I _strongly_ agree with), but many folks want our "calendar" style which most closely aligns with the CAGR calculation (compounded annual growth rate).

**Comment by twiecki** [comment]
@justinlent what's your updated opinion on this?

**Comment by justinlent** [comment]
I think my updated opinion is to simplify it all and remove the returns_style keyword where ever it is currently, and just default to CAGR method for all returns computations, and deal with the edge cases (like Sharpe Ratio, which uses arithmetic returns) locally within these specific functions.

I'd be fine with closing this current issue and re-opening in favor of a new one based on what I describe here.  

Cool with you @twiecki  ?

**Comment by twiecki** [comment]
Sounds great.
