### ISSUE TITLE
annual_returns calculation for 'calender' style is not accurate

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#212]
I don't believe it computes the average annual return correctly since it currently just divides by num_years, where it should be computing the geometric return along the lines of:  

total_return = (portfolio_end_value - portfolio_start_value) / portfolio_start_value
annual_return = (1+total_return) ^ (1/num_years) - 1

@twiecki Thoughts?

**Comment by justinlent** [comment]
which is just the CAGR (compounded annual growth rate) calculation, so maybe we should change the method name from calendar -> CAGR.  Looks like folks in the Q forums refer to this method using CAGR. As well the annual return from CAGR is the same as "compound" which I somewhat proved to myself in an Excel spreadsheet, so having this style may just be redundant unless I'm missing an edge case or something.

**Comment by twiecki** [comment]
We're on the same page and should fix that asap.

**Comment by justinlent** [comment]
my current working opinion is we should simplify annual_return to simply be CAGR, so change the signature from:

```def annual_return(returns, style='compound', period=DAILY)```

to ```def annual_return(returns, period=DAILY)```

and then only have it return the CAGR result which is the fixed version of 'calendar' as described earlier in this thread

**Comment by twiecki** [comment]
I agree with that.

**Comment by twiecki** [comment]
Assigning to you as you worked most closely with this.

**Comment by justinlent** [comment]
@twiecki can you do a quick code review of my implementation in this PR https://github.com/quantopian/pyfolio/pull/234

**Comment by twiecki** [comment]
Closed via #234
