### ISSUE TITLE
Fix Sharpe ratio calculation

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#213]
Should be: mean(daily returns - risk_free) / std(daily returns - risk_free) * np.sqrt(252)

Adding for reference:
https://web.stanford.edu/~wfsharpe/art/sr/sr.htm

CC @justinlent

**Comment by justinlent** [comment]
+1
Outstanding question is how to handle the risk_free rate timeseries when it is commonly pulled in as an annual yield.

E.g.  If the daily value in the risk_free timeseries is 4% annual yield, is the daily yield:
a)  4% / 252
b) (1 + 4%)^(1/252) - 1

My thought is (b)

**Comment by twiecki** [comment]
Yep, agree with b:
```python
