### ISSUE TITLE
Add validation of inputs

### ISSUE THREAD

**Issue by a-campbell** [quantopian/pyfolio#224]
To ensure pyfolio is being passed correctly formatted inputs, it might be helpful to run returns, positions, and transactions through validation functions before the rest of pyfolio runs. These functions would check the column names, datatypes, datetime formats, and presence of nans in the returns, positions, transactions and gross leverage DataFrames. 

Checking inputs upfront will allow us to show the user better error messaging when an improperly formatted input is passed. These validation functions could also be used in the integration tests of libraries that depend on pyfolio. If/when we change the input requirements of pyfolio, we'd wan't deprecated integrations to fail elegantly in tests, rather than hard to decipher seaborn tracebacks in production.

**Comment by twiecki** [comment]
Related https://github.com/quantopian/pyfolio/issues/211
