### ISSUE TITLE
I can't run pyfolio in a virtualenv on OSX

### ISSUE THREAD

**Issue by adzuci** [quantopian/pyfolio#225]
I think the root issue here is that virtualenv on OSX by default does not use a framework build of python & seaborn needs that at import time.

There are some work arounds here, but none of them seem like an ideal solution, has anyone worked around this in a virtualenv? 
http://matplotlib.org/faq/virtualenv_faq.html

```
import seaborn as sns
```
Results in:
```
Traceback (most recent call last):
  File "/Users/adzuci/Documents/code/pyfolio/pyfolio/plotting.py", line 20, in <module>
    import seaborn as sns
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/seaborn/__init__.py", line 1, in <module>
    from .rcmod import *
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/seaborn/rcmod.py", line 5, in <module>
    from . import palettes
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/seaborn/palettes.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/adzuci/.virtualenvs/pyfolio/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

I'm using these versions:
```
pip freeze | grep "seaborn\|matplotlib"
matplotlib==1.5.0
seaborn==0.6.0
```

Related: https://github.com/mwaskom/seaborn/issues/790

**Comment by twiecki** [comment]
I think it's a matplotlib issue, not a pyfolio one.

**Comment by adzuci** [comment]
I think the framework issue is a matplotlib+osx issue, but when the matplotlib backend is instantiated in the `__init__.py` file of pyfolio I can't just set the backend in the test files with `matplotlib.use('TkAgg')`.  I was looking for a way to make pyfolio more osx friendly that didn't involve changing the matplotlib backend, but I think that might require a change to seaborn or matplotlib.  My thought was that if seaborn stopped calling out to the backend at import time I would be able to work around it better, but maybe that's the wrong idea?

@gwulfs helped me work around the issue for now by overriding my local matplotlib backend:
http://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python

```
echo "backend: TkAgg" > ~/.matplotlib/matplotlibrc
```

I should have included that I was running into this issue running tests & that I reprod it on another osx machine:

```
workon pyfolio
pip install -e .
pip install patsy nose nose_parameterized runipy
nosetests pyfolio/tests
```

**Comment by twiecki** [comment]
Thanks posting the work-around.

**Comment by abhijeetkalyan** [comment]
@adzuci @twiecki can we add this to the README? I just ran into this same issue

**Comment by adzuci** [comment]
I put up a PR for https://github.com/quantopian/pyfolio/pull/257/files, I don't like the idea of adding a work around like this though unless there is no way to make it "just work".
