### ISSUE TITLE
Add Information Ratio to tearsheet (the type from Fundamental Law of Active Management)

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#227]
described here:  
http://www.barra.com/newsletter/nl163/SevIns3NL163.asp

**Comment by twiecki** [comment]
Nice one. How are "independent bets per year" computed? Just number of trades?

**Comment by justinlent** [comment]
I think it's definitely tough to infer # of independent bets without knowing underlying algo logic, but I'm thinking something along the lines of the using the roundtrip analysis you've done which, if I recall, infers # of trades per month from parsing the buy/sell transactions.  We could then just multiply # of trades per month by 12 to get an approximation of 'independent bets per year.'

**Comment by georgh0021** [comment]
Implemented in the round trip tear sheet.
