### ISSUE TITLE
Remove requirement of gross_leverage and instead compute from positions.

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#231]
We already compute the similar net leverage in the long-short plot: https://github.com/quantopian/pyfolio/blob/master/pyfolio/pos.py#L62.

**Comment by georgh0021** [comment]
Fixed in [this commit](https://github.com/quantopian/pyfolio/commit/e2bf7fc0c52095addb0229f3dbbe2929b94afd31#diff-dd656075c4a67ac1cd34b18065e18791R633)
