### ISSUE TITLE
Pandas 0.17 is suppressing x axis tick labels when plotting time series

### ISSUE THREAD

**Issue by a-campbell** [quantopian/pyfolio#236]
The x axis labels disappeared when I upgraded from pandas 0.16 to 0.17. 

![screenshot 2015-12-03 12 53 38](https://cloud.githubusercontent.com/assets/6374406/11569676/2788ae14-99c1-11e5-88e2-ccdfa9142f0d.png)

**Comment by twiecki** [comment]
Should we include this in 0.4 @a-campbell?

**Comment by a-campbell** [comment]
I'd say so. I'll take a deeper look now.

**Comment by a-campbell** [comment]
fixed in 87a40d1386621248602423a7706f8a59dff59dd9
