### ISSUE TITLE
Add stock-wise performance attribution

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#238]

**Comment by a-campbell** [comment]
How would this differ from the PnL attribution in the round trips tearsheet? 

I've been wanting a way to know the profit breakdown by name for specific time spans in the backtest.

**Comment by twiecki** [comment]
The round-trip has a similar analysis but it's not very general (because the round-trip is not very general) and makes a few assumptions.

We could compute something like this:
`returns_per_pos = daily_positions_alloc * daily_returns`
That way we get daily returns per position (or sector) without requiring any pricing information. Then we can aggregate over time to see which positions had the highest median returns etc. 

It's not perfect though as a large swing in a small part of the portfolio could have the same effect as small swing in a large part. Prices would be better. 

Thoughts?

**Comment by a-campbell** [comment]
Makes sense. Would be great to give the user the ability to roll these daily returns per position into weekly, monthly, and yearly returns too. 

Alternatively, we could back out the daily price changes of individual names using amounts from the transactions df and values from the positions df. That might get a little messy, though.

**Comment by georgh0021** [comment]
Sounds like #400 will address this!
