### ISSUE TITLE
plot_rolling_returns() Y axis is not correct

### ISSUE THREAD

**Issue by jmccorriston** [quantopian/pyfolio#255]
https://secure.helpscout.net/conversation/148743379/8198/?folderId=605902:

The Y axis is too high or totally jibberish for plot_rolling_returns(). The following code gives crazy Y axis values, despite qrets and pvr looking reasonable. As well, the actual lines on the plot seem correct (proportional to the difference in their value), so I believe just the Y axis ticks are wrong.
```
backtest = get_backtest('5637da7c2fe6e438be119651')
import pyfolio as pf
qrets = backtest.daily_performance.returns # Quantopian returns
start = backtest.daily_performance.starting_cash[1] # Starting capital like 100000, probably a better way
cash_spent = start - min(backtest.daily_performance.starting_cash) # Most spent so far, should not see the future
max_cash = max(0, start - cash_spent) # Cash spent, of start or over, a logic puzzle for the mind
max_shorts = abs( backtest.positions.min().amount ) # Lowest single short as a positive value, should be all shorts
riskhi = max(max_cash, max_shorts) # Should be highest of cash spent or shorting
pvr = (qrets * start) / riskhi # (portf - start) / riskhi
pf.plot_rolling_returns(qrets, pvr) # Plot Q returns and PvR
```

This examples has a more reasonable looking Y axis, but still wrong:
```
backtest = get_backtest('56045520824b7f0e1dae20fd')
import pyfolio as pf
qrets = backtest.daily_performance.returns # Quantopian returns
start = backtest.daily_performance.starting_cash[1] # Starting capital like 100000, probably a better way
cash_spent = start - min(backtest.daily_performance.starting_cash) # Most spent so far, should not see the future
max_cash = max(0, start - cash_spent) # Cash spent, of start or over, a logic puzzle for the mind
max_shorts = abs( backtest.positions.min().amount ) # Lowest single short as a positive value, should be all shorts
riskhi = max(max_cash, max_shorts) # Should be highest of cash spent or shorting
pvr = (qrets * start) / riskhi # (portf - start) / riskhi
pf.plot_rolling_returns(qrets, pvr) # Plot Q returns and PvR
```

**Comment by twiecki** [comment]
Can you paste the plots?

**Comment by twiecki** [comment]
Ping @jmccorriston

**Comment by jmccorriston** [comment]
Sorry @twiecki , must have missed the email, here are the plots:
First:
![image](https://cloud.githubusercontent.com/assets/4500507/12484050/513790f0-c026-11e5-96bf-0c2faec27e9b.png)

Second:
![image](https://cloud.githubusercontent.com/assets/4500507/12484063/6128928e-c026-11e5-8258-34f4c1d09005.png)

**Comment by twiecki** [comment]
Is that fixed with the new pyfolio? Seems like the datetimes get mangled somehow.

**Comment by jmccorriston** [comment]
Is the new version on Q prod?

**Comment by twiecki** [comment]
Should be, yeah.

**Comment by jmccorriston** [comment]
Getting the same result.

**Comment by twiecki** [comment]
That's probably a bug in the input data. We're cumulating the input so you can't plug in an arbitrary time-series. You'd have to call ax.plot(mytimeseries) outside of `plot_cum_returns`.
