### ISSUE TITLE
plot_monthly_returns_heatmap under different Matplotlib version

### ISSUE THREAD

**Issue by leoleolam** [quantopian/pyfolio#263]
When I try to plot the heatmap under Matplotlib 1.4.3 it is perfectly fine. Returns number are displayed well in each box and the y axis shows year labels clearly. However, when I switch to use Matplotlib 1.5.0, the return number are gone and y-axis years are messed up. I used seaborn 0.6.0 in both cases.

I am wondering if anyone notice this and advise.

Thanks

**Comment by twiecki** [comment]
Can you post the image that's wrong?

**Comment by leoleolam** [comment]
![image](https://cloud.githubusercontent.com/assets/15147146/11963869/b4119f4e-a8b7-11e5-91ea-cdddda3de189.png)

please see the sample above

**Comment by twiecki** [comment]
Was seaborn bug https://github.com/mwaskom/seaborn/issues/619
