### ISSUE TITLE
Position weighting alpha/attribution analysis

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#265]
Using the zipline trades/transactions/order data, to generate simple baseline portfolios based on the trades.  Then compare these baseline portfolios to the actual algo to see if the algo is actually generating alpha based on the position weights it chooses.

The baseline portfolios could be generated in various ways, such as:
- [ ] equal-weight  (this is the most basic case, and should be implemented 1st) 
- [ ] market-cap weighted portfolio
- [ ] volatility weight portfolio

**Comment by georgh0021** [comment]
Looks like this would be solved by #400!
