### ISSUE TITLE
User Request: Days Held by Symbol

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#269]
Days Held by Symbol
This answers the question: how many days did we hold the symbol

**Comment by georgh0021** [comment]
@justinlent Responding a year late, but it sounds like `pyfolio.round_trips.extract_round_trips` would do what you need. It produces a DataFrame, with one column giving the duration of the round trip. Code [here](https://github.com/quantopian/pyfolio/blob/master/pyfolio/round_trips.py#L151) and documentation [here](https://quantopian.github.io/pyfolio/notebooks/round_trip_example/)
