### ISSUE TITLE
User Request: CAGR for the most recent 3, 5, and 10 year periods

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#271]
CAGR for the most recent 3, 5, and 10 year periods
This would facilitate comparisons with "real world" strategies that all use these time frames for performance reporting.

**Comment by georgh0021** [comment]
Both [pyfolio](https://github.com/quantopian/pyfolio/blob/f0e8afc3b2f505ab03637547223cf86c22c8eedb/pyfolio/timeseries.py#L87) and [empyrical](https://github.com/quantopian/empyrical/blob/master/empyrical/stats.py#L235) can compute CAGR, although the function is deprecated in pyfolio.
