### ISSUE TITLE
pyfolio environment setup with git, to contribute

### ISSUE THREAD

**Issue by garyha** [quantopian/pyfolio#275]
Files using 'pip install pyfolio' may be different than cloning https://github.com/quantopian/pyfolio
(One with a directory called data the another a directory called examples)
Different locations too.
Also I have c:\python27 and another install of Python at c:\anaconda
For setup/run of ipython for notebooks in a browser, I did 'pip install jupyter' and that seemed to have taken care of a few things.
Generally complex, lots of webpages, errors, fixed, new errors.
These might be n00b concerns, however, sometimes this feels like Little Software Developer on the Prairie. Just wants some goatmilk. Start by sharpening tools, cut down trees to make fenceposts, saddle up, trip to town to buy wire, pip install, plant grass, read a manual for that, forgot nails, back to town, seems good, module 'utils' not found, ask the town oracle jackoverflow, knows everything, doesn't know, weird, last resort just head off to the saloon, or post a question.

Would love to see a list of steps that could streamline an integrated environment with python, git and pyfolio when one might like to contribute.

**Comment by twiecki** [comment]
There are plenty of github tutorials, e.g. https://guides.github.com/activities/hello-world/. Specifically you'll want to fork this repo, commit your changes, and then submit a pull request.

**Comment by twiecki** [comment]
Closing as it's not a pyfolio issue but feel free to comment/ask in this thread.

**Comment by garyha** [comment]
Ok, forget about git then.

C:\Python27\Lib\site-packages\pyfolio>ipython notebook examples\quantopian_example.ipynb
[I 01:08:18.476 NotebookApp] Serving notebooks from local directory: C:\Python27\Lib\site-packages\pyfolio\examples
[I 01:08:18.477 NotebookApp] 0 active kernels
[I 01:08:18.483 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 01:08:18.484 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 01:08:24.095 NotebookApp] Notebook quantopian_example.ipynb is not trusted
[I 01:08:30.746 NotebookApp] Kernel started: 1387005f-e3a1-4c0c-a386-6e2659d36666

http://localhost:8888/notebooks/quantopian_example.ipynb

Cursor in the first cell.
Shift-<Enter>

In [1]:

backtest = get_backtest('55f8c9acea2cd40e0029c206')

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-40c751a1fb66> in <module>()
----> 1 backtest = get_backtest('55f8c9acea2cd40e0029c206')

NameError: name 'get_backtest' is not defined

**Comment by twiecki** [comment]
`get_backtest` is not available outside of quantopian. You need a zipline backtest or local files. See e.g. http://quantopian.github.io/pyfolio/zipline_algo_example/

In regards to the pull-request, you can just post the function with docs here and I can include it. We have functions that take `returns`, `positions`, and `transactions`.

**Comment by garyha** [comment]
I see:
returns, positions, transactions, gross_lev = pf.utils.extract_rets_pos_txn_from_zipline(backtest)
...and that function is in pyfolio. Beautiful example at that link.

Great, and that route for pull is huge relief. Thanks.
