### ISSUE TITLE
Add rolling annual volatility plot

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#278]
Similar to the rolling Sharpe Ratio plot, but just rolling annual volatility (which is simply the denominator from Sharpe Ratio).  As well, overlay the rolling annual volatility of SPY, say, in a lighter color, like gray.  This will allow easy visual comparison of an algo's volatility with the volatility of the US Stock Market (SPY)

**Comment by hkopp** [comment]
I'll take a look at the first part, as this seems very basic.
