### ISSUE TITLE
compute "volatility beta" of an algo to a benchmark like SPY

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#280]
Idea here being:  How is the volatility of my trading strategy related to the volatility of the broad stock market.

A very simple, initial implementation might simply be computing the beta of the absolute returns of the algo versus the absolute returns of the benchmark.  Something like this:
`ols( abs(algo_returns), abs(SPY_returns) )`

**Comment by georgh0021** [comment]
#278 addresses this idea. If anything, reducing the relationship between algo volatility and SPY volatility is a bit reductive: better to produce a plot.
