### ISSUE TITLE
nb question: how to extract Transaction Details and Daily Positions & Gains data tables

### ISSUE THREAD

**Issue by ckir** [quantopian/pyfolio#283]
Having a zipline pickle generated as

```
run_algo.py -c dual_moving_average.conf -o dual_moving_average.pickle
```

How can i print the Transaction Details and Daily Positions & Gains data tables as shown on Quantopian's web site after a Full Backtest run ??

I'm looking for a python not ipython solution (i don't need the plots at this stage) and to format data as json if possible.

**Comment by twiecki** [comment]
@ckir See here for an example: http://quantopian.github.io/pyfolio/zipline_algo_example/

You can either run your backtest from within python (as the example shows), or load the pickle file back into python and call `pf.utils.extract_rets_pos_txn_from_zipline(backtest)`

**Comment by ckir** [comment]
@twiecki Hi,

Please have a look at the following images to get an idea of what I’m looking for

[Transaction Details ](https://drive.google.com/file/d/0B_aFZjJihx3JRlc4aVRYaU5BYm8/view?usp=sharing)
[Daily Positions - Gains ](https://drive.google.com/file/d/0B_aFZjJihx3JWnBlQ2dFRWRLSDQ/view?usp=sharing)

I'm not a python programmer but I like to read a lot. So far I tried:

    import cPickle as pickle
    import pyfolio as pf

    with open('./dual_moving_average.pickle', 'rb') as handle:
        perf_manual = pickle.load(handle)

    returns, positions, transactions, gross_lev = pf.utils.extract_rets_pos_txn_from_zipline(perf_manual)

    pf.create_full_tear_sheet(returns, positions=positions, transactions=transactions,
                          gross_lev=gross_lev)

    pf.create_position_tear_sheet(returns, positions=positions)

They both work but I' cant find the tables I'm looking for.

Any ideas ??

**Comment by twiecki** [comment]
`positions` and `transactions` are not what you're looking for?

**Comment by ckir** [comment]
@twiecki I'm missing a way to convert "sid" to actual symbol.

When I look into transactions (converted to json as [transactions.to_json(date_format='iso')] I can see records containing "sid" but not the actual symbol

    "2002-02-11T21:00:00.000Z": [
        {
            "amount": 100,
            "commission": 3.0,
            "dt": "2002-02-11T00:00:00.000Z",
            "order_id": "346acd16d7c04a4cb4ba843e14b5b38e",
            "price": 1.682408,
            "sid": 0
        }
    ],

For positions (converted to json as [positions.to_json(date_format='iso')] the entries look like again  I can see records containing "sid" but not the actual symbol

    "2002-02-12T21:00:00.000Z": [
        {
            "amount": 100,
            "cost_basis": 1.682408,
            "last_sale_price": 1.634548,
            "sid": 0
        }
    ],

Furthermore I assumed (guess its my mistake) that since the data appears ready on quantopian's site and pyfolio is doing the analysis, there is a method that produces those results and I don't have to write one. Anyway. My question is: How do I get symbol from sid

**Comment by twiecki** [comment]
I meant `positions` and `transactions` after having called `returns, positions, transactions, gross_lev = pf.utils.extract_rets_pos_txn_from_zipline(perf_manual)`. Is that the output?
