### ISSUE TITLE
Issue when running Bayesian Tear sheet ValueError: On entry to DGELSD parameter number 4 had an illegal values:open 

### ISSUE THREAD

**Issue by bpajusco** [quantopian/pyfolio#285]
I've come across this error when running a tear sheet for a strategy backtest. The results aren't generated using zipline data or any of the Quantopian infrastructure and the equity curve doesn't look obviously wrong to me (i.e. there are no NaNs or Inf in the series). It's pretty hard to figure out what could be the reason for the error, besides the obvious observation that it has to do with failing to solve the SVD for the alpha/beta model. 

Here is the full stack for completeness:

ValueError                                Traceback (most recent call last)
<ipython-input-31-452400a15b56> in <module>()
      4 rets = rets.tz_localize('UTC')
      5 out_of_sample = rets.index[-66]
----> 6 pf.create_bayesian_tear_sheet(rets, live_start_date=out_of_sample, stoch_vol=True)

/home/bpajusco/anaconda3/lib/python3.5/site-packages/pyfolio/plotting.py in call_w_context(_args, *_kwargs)
     45         if set_context:
     46             with context():
---> 47                 return func(_args, *_kwargs)
     48         else:
     49             return func(_args, *_kwargs)

/home/bpajusco/anaconda3/lib/python3.5/site-packages/pyfolio/tears.py in create_bayesian_tear_sheet(returns, benchmark_rets, live_start_date, samples, return_fig, stoch_vol)
    813     trace_alpha_beta = bayesian.run_model('alpha_beta', df_train,
    814                                           bmark=benchmark_rets,
--> 815                                           samples=samples)
    816     previous_time = timer("running alpha beta model", previous_time)
    817 

/home/bpajusco/anaconda3/lib/python3.5/site-packages/pyfolio/bayesian.py in run_model(model, returns_train, returns_test, bmark, samples, ppc)
    580     if model == 'alpha_beta':
    581         model, trace = model_returns_t_alpha_beta(returns_train,
--> 582                                                   bmark, samples)
    583     elif model == 't':
    584         model, trace = model_returns_t(returns_train, samples)

/home/bpajusco/anaconda3/lib/python3.5/site-packages/pyfolio/bayesian.py in model_returns_t_alpha_beta(data, bmark, samples)
     87         X.loc[:, 'ones'] = 1.
     88         y = data_no_missing
---> 89         alphabeta_init = np.linalg.lstsq(X, y)[0]
     90 
     91         alpha_reg = pm.Normal('alpha', mu=0, sd=.1, testval=alphabeta_init[-1])

/home/bpajusco/anaconda3/lib/python3.5/site-packages/numpy/linalg/linalg.py in lstsq(a, b, rcond)
   1917         work = zeros((lwork,), t)
   1918         results = lapack_routine(m, n, n_rhs, a, m, bstar, ldb, s, rcond,
-> 1919                                  0, work, lwork, iwork, 0)
   1920     if results['info'] > 0:
   1921         raise LinAlgError('SVD did not converge in Linear Least Squares')

ValueError: On entry to DGELSD parameter number 4 had an illegal value

**Comment by twiecki** [comment]
Hm, this is an odd one. It actually is inside `np.linalg.lstsq(X, y)[0]`, not the Bayesian model. That still strongly suggests a data error. If you enable pdb and drop in that call print X and y should make it obvious.

**Comment by bpajusco** [comment]
Thanks Thomas.

It was indeed a data issue and to be precise it was down to a mismatch 
between result and benchmark data as I've run the analysis on a global 
portfolio but compared with the S&P which doesn't have data on US 
holidays. I've put in a hack using .fillna(EPSILON) where the constant 
has next to zero value and everything worked fine. Incidentally, I had a 
bit of an issue on plot_stochastic_volatility as the difference in 
source data made indexing the series a bit tricky. In the end I've 
changed data.abs().plot(ax=ax) to ax.plot(data.index.to_pydatetime(), 
data.abs()) and that made matplotlib much happier. I don't know if my 
experience warrants a change of code in the official library though.

Thanks again,
Bruno
