### ISSUE TITLE
pull request #286 messes things up

### ISSUE THREAD

**Issue by mickeydonkey** [quantopian/pyfolio#288]
this PR change the output of pandas object to `np.ndarray`, which misses the information of what each number stands for.  
take `perf_stats` as example, before `np.round` opearation:
![image](https://cloud.githubusercontent.com/assets/12562760/14164589/56a31dcc-f733-11e5-8fe6-7d04cc0284e5.png)
after round:
![image](https://cloud.githubusercontent.com/assets/12562760/14164599/6dccd934-f733-11e5-8ad3-d2532af3c397.png)

I suggest use [the pandas way to round number](http://pandas.pydata.org/pandas-docs/version/0.18.0/generated/pandas.DataFrame.round.html)

**Comment by twiecki** [comment]
Thanks @mickeydonkey. I agree, will fix that soon.

**Comment by twiecki** [comment]
@mickeydonkey Can you confirm that #289 fixes the issue for you?

**Comment by mickeydonkey** [comment]
Rounding number is OK now, and tables looks pretty in notebook. But PR [#289 ](https://github.com/quantopian/pyfolio/pull/289) introduces a new issue to me. that is I usually work with IPython console(Spyder IDE actually), and display some HTML object doesn't get any useful output, it looks like this:
![image](https://cloud.githubusercontent.com/assets/12562760/14175294/b738fba4-f77c-11e5-90d1-34ca82bfa64e.png)
If I was right, you tried to differentiate python console and notebook environment by `get_ipython()` , but it won't work in this case.

**Comment by twiecki** [comment]
Hm, thanks, have to find a better way.

**Comment by mickeydonkey** [comment]
I opened a new issue for this, [#291](https://github.com/quantopian/pyfolio/issues/291)

**Comment by twiecki** [comment]
Thanks.
