### ISSUE TITLE
display some HTML object doesn't get any useful output in IPython console

### ISSUE THREAD

**Issue by mickeydonkey** [quantopian/pyfolio#291]
PR [#289](https://github.com/quantopian/pyfolio/pull/289) introduces a new issue to me. that is when working with IPython console, display some HTML object doesn't get any useful output, it looks like this:
![image](https://cloud.githubusercontent.com/assets/12562760/14175638/d1d0e74a-f77e-11e5-9e30-19d494da912a.png)

**Comment by mickeydonkey** [comment]
@twiecki What if use `display(df)` instead of display(df.to_html()),
for notebook:
![image](https://cloud.githubusercontent.com/assets/12562760/14176177/48e210ae-f782-11e5-85a3-ebc86b2a3b9a.png)
for IPython console:
![image](https://cloud.githubusercontent.com/assets/12562760/14176192/5bc33716-f782-11e5-8283-de5a4c2b7788.png)
Now, they are both happy;)

**Comment by twiecki** [comment]
@mickeydonkey Thanks for looking into that, will change. Do we even need the `get_ipython()` hack then?

**Comment by twiecki** [comment]
Did you check whether that works from inside a function?

**Comment by mickeydonkey** [comment]
I checked the following code for print inside a function, and it works as before:
`from IPython.display import display
df = pd.DataFrame([1,2],[3,4])
def smart_print(a):
    display(pd.DataFrame([1,2],[3,4]))
smart_print(df)
`

**Comment by twiecki** [comment]
Sweet! Want to do a PR?

**Comment by mickeydonkey** [comment]
Sorry, I haven't make any commit yet. in addition, I am not familiar with code styling stuff like PEP8. So you'd better fix it yourself. Thanks

**Comment by mickeydonkey** [comment]
even if I do hope I could contribute the code.....

**Comment by twiecki** [comment]
Much simpler, thanks for your help!
