### ISSUE TITLE
Update Long+Short+Cash plot y-values to match Gross Leverage plot

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#30]
might make more sense visually is have the long+short+cash plot y-axis values match up with the gross exposure y-axis

**Comment by twiecki** [comment]
What's weird is that we already do that: https://github.com/quantopian/pyfolio/blob/master/pyfolio/pos.py#L62

**Comment by humdings** [comment]
Fixed via https://github.com/quantopian/pyfolio/pull/147
