### ISSUE TITLE
Please avoid ` from packages import *`

### ISSUE THREAD

**Issue by nooperpudd** [quantopian/pyfolio#315]
I want to import some function in the pyfolio.
but if I try to import pyfolio , another python process will run a service just like ipython progress  and 
suspend the process.

better to avoid `from packages import *` in the `__init__.py` file or in other python file.

I think the problems should be in `seaborn`.

**Comment by twiecki** [comment]
Thanks for reporting.

> but if I try to import pyfolio , another python process will run a service just like ipython progress and 
suspend the process

Not sure what you mean here, which process? If there's a problem with importing seaborn, pyfolio won't be functional to begin with.
