### ISSUE TITLE
I found an error that "AttributeError: 'Series' object has no attribute 'rolling'"

### ISSUE THREAD

**Issue by niumuguang** [quantopian/pyfolio#316]
My environment:
numpy (1.11.1)
pandas (0.17.1)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (5.0.0)
jupyter-core (4.1.0)
rtslib-fb (2.1.57)
scikit-learn (0.17.1)
scipy (0.17.1)
seaborn (0.7.1)
seobject (0.1)
sepolicy (1.1)

error context:
/usr/lib64/python2.7/site-packages/pandas/core/generic.pyc in **getattr**(self, name)
   2358                 return self[name]
   2359             raise AttributeError("'%s' object has no attribute '%s'" %
-> 2360                                  (type(self).**name**, name))
   2361 
   2362     def **setattr**(self, name, value):

AttributeError: 'Series' object has no attribute 'rolling'

![error](https://cloud.githubusercontent.com/assets/3469819/17125126/7b652a32-5323-11e6-8638-9fa42a043605.JPG)

I modify the file named timeseries.py at row 1100 like this

![modified](https://cloud.githubusercontent.com/assets/3469819/17125145/9b13afd4-5323-11e6-83de-b69af5541445.JPG)

**Comment by twiecki** [comment]
You need to update `pandas` to 0.18 or higher.
