### ISSUE TITLE
Documentation about metrics

### ISSUE THREAD

**Issue by junajo10** [quantopian/pyfolio#318]
Hello,

I am new using Pyfolio, is there any place where i can find documentation about these metrics?
annual_return  
annual_volatility  
sharpe_ratio  
calmar_ratio  
stability  
max_drawdown  
omega_ratio  
sortino_ratio  
skewness  
kurtosis  
alpha  
beta

**Comment by twiecki** [comment]
Good point, I moved this over here: https://github.com/quantopian/qrisk/issues/12

**Comment by twiecki** [comment]
Good point, will add these.

**Comment by ahgnaw** [comment]
@junajo10 Here is the link to the empyrical documentation. This library is used in the website and in pyfolio for risk calculations. 

http://quantopian.github.io/empyrical/appendix.html#

**Comment by junajo10** [comment]
Thanks, do you know if these metrics could be used with intraday strategies? I am using tick data. If you think there are better metrics than these ones, please let me know.
