### ISSUE TITLE
Tearsheets can't be generated for results with no EOD positions

### ISSUE THREAD

**Issue by jmccorriston** [quantopian/pyfolio#321]
https://github.com/quantopian/pyfolio/blob/62aaaad446c959061ed96efdaac5ec655686db54/pyfolio/utils.py#L412

A non-empty positions DF is required in order to create a tearsheet. This means that an algorithm which closes all of it's positions before the end of each day cannot be analyzed with a tearsheet.

**Comment by gusgordon** [comment]
Yeah, we can fix this by constructing `positions` from `transactions`, which will give us intraday data. I'm gonna mark this as high priority.
