### ISSUE TITLE
returns are none simple, which statistics apply?

### ISSUE THREAD

**Issue by js190** [quantopian/pyfolio#322]
Hi there,
my return series consists of actual returns. This is because we are settling a commodity against a daily auction.

Which of the statistics in pyfolio are applicable to actual returns?
I'm a newbie with regard to portfolio analysis so any pointers appreciated, thanks!

**Comment by twiecki** [comment]
Not sure what you mean with "actual returns", as opposed to what?

**Comment by js190** [comment]
as opposed to simple returns

**Comment by js190** [comment]
am i making sense? 
any pointers appreciated :)

**Comment by twiecki** [comment]
Can't you convert to simple returns?
