### ISSUE TITLE
User request: Add metrics e.g. % winning trades, Avg trade duration

### ISSUE THREAD

**Issue by alizrrao** [quantopian/pyfolio#348]
Commonly used system metrics include:

Gross profit
Gross loss
Profit factor (= gross profit / gross loss)
Total number of trades
Percent profitable
Winning trades
Losing trades
Average trade net profit
Average winning trade
Average losing trade
Largest winning trade
Largest losing trade
Ratio average win : average loss (or W:L ratio)
Average trade duration
Average trade duration in winning trades
Average trade duration in losing trades

These would be great metrics to include to verify whether the system logic includes stop losses and follows the rule: cut the losses short and let profits run.

**Comment by twiecki** [comment]
Those should all be part of the round-trip tear sheet.
