### ISSUE TITLE
Plot for Cone displayed at 0 line, using single_stock_example notebook

### ISSUE THREAD

**Issue by treydog999** [quantopian/pyfolio#352]
I am using the single_stock_example notebook and have changed the symbol to IBM. Now when I run this code, the blue cone and the out of sample plot are not aligned. The blue cone is rather on the 0 line.

    %matplotlib inline
    import pyfolio as pf
    stock_rets = pf.utils.get_symbol_rets('IBM')
    pf.create_returns_tear_sheet(stock_rets, live_start_date='2015-12-1')

![image](https://cloud.githubusercontent.com/assets/6192612/20475109/eb180726-b004-11e6-9fc5-242845d17152.png)

![image](https://cloud.githubusercontent.com/assets/6192612/20475118/f42a3744-b004-11e6-8ffb-78e8da8d7006.png)

**Comment by twiecki** [comment]
Thanks for reporting. @ahgnaw any ideas?

**Comment by ahgnaw** [comment]
@treydog999 @twiecki This issue was solved by @gusgordon (https://github.com/quantopian/pyfolio/commit/38e265caaa0cdd094490dd19caaa207868fdace6)already. Unfortunately the fix has not made it to the pypi repository yet. @treydog999 the issue goes away if you use the latest pyfolio version on github.
