### ISSUE TITLE
Default plotting style context doesn't affect the facet colour

### ISSUE THREAD

**Issue by luca-s** [quantopian/pyfolio#361]
The[ plotting.context function](https://github.com/quantopian/pyfolio/blob/master/pyfolio/plotting.py#L62) tries to set the defaults for 'axes.facecolor' and 'figure.facecolor' using seaborn.plotting_context(), but it cannot work as  that function is intended to control the **scale** of plot elements, not those properties. The seaborn.axes_style()  fucntion should be used instead. See http://seaborn.pydata.org/tutorial/aesthetics.html

**Comment by luca-s** [comment]
The fix can be ported from [here](https://github.com/quantopian/alphalens/pull/125) as the code is identical

**Comment by georgh0021** [comment]
@luca-s sounds like a plan, want to submit a PR?

**Comment by luca-s** [comment]
sure!

**Comment by twiecki** [comment]
Closed by #361.
