### ISSUE TITLE
There's no such a function portfolio_returns_metric_weighted in timeseries

### ISSUE THREAD

**Issue by FitzroyCM** [quantopian/pyfolio#370]
I was trying to run this example Fama-French Benchmark.ipynb, but found there's no such a function portfolio_returns_metric_weighted in timeseries.py. Maybe I'm missing something, but could anyone clarify this for me?

Thanks,
FCM

**Comment by twiecki** [comment]
It seems like that NB is out-of-date.

**Comment by georgh0021** [comment]
Sounds like the problem has been resolved, closing this issue now.
