### ISSUE TITLE
Pandas 0.20.x compatibility

### ISSUE THREAD

**Issue by mckelvin** [quantopian/pyfolio#378]
Pandas 0.20.x was [released](http://pandas.pydata.org/pandas-docs/stable/whatsnew.html#v0-20-1-may-5-2017) a few days ago. There're some major changes which break pyfolio.

**Comment by twiecki** [comment]
Thanks @mckelvin. Any help would be much appreciated.

**Comment by twiecki** [comment]
Fixed by #395.
