### ISSUE TITLE
Fama-French File Transfer Blocked

### ISSUE THREAD

**Issue by citynorman** [quantopian/pyfolio#380]
I'm getting a download error for the FF data library and I can't turn off the FF plots have to manually deactivate them by commenting out the code.

http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Research_Data_Factors_daily_CSV.zip
File Transfer Blocked
Transfer of the file you were trying to download or upload has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.
File name: F-F_Research_Data_Factors_daily_CSV.zip

Be good to either have those on some sort of S3 mirror or be able to turn off the FF plots.

```
def create_returns_tear_sheet(returns, positions=None,
                              live_start_date=None,
                              cone_std=(1.0, 1.5, 2.0),
                              benchmark_rets=None,
                              bootstrap=False,
                              return_fig=False,
                              plot_ff=True):
[...]
    if plot_ff:
        plotting.plot_rolling_fama_french(
            returns, ax=ax_rolling_risk)

```
[see additional debug details here ](https://github.com/quantopian/pyfolio/issues/153)

**Comment by georgh0021** [comment]
Hi there @citynorman, are you still experiencing this problem? Pandas data reader has just been fixed.

**Comment by georgh0021** [comment]
Sounds like there isn't a problem anymore, closing this issue

**Comment by citynorman** [comment]
This seems to have gone away but I'd still like the flexibility to disable the external dependency.

**Comment by georgh0021** [comment]
@citynorman could you open a new issue for disabling a the FF plots please? Sounds like an interesting point to discuss.
