### ISSUE TITLE
Bayesian Tear

### ISSUE THREAD

**Issue by bpajusco** [quantopian/pyfolio#381]
When using a custom benchmark or when returns series dates don't match exactly those of the benchmark series Pymc3 optimisation fails to calculate MAP assignments and falls over. To fix this problem is sufficient to amend line 88 and 96 in bayesian.py to deal with NaN values.

**Comment by twiecki** [comment]
@bpajusco Thanks! Want to submit a PR with the fix?

**Comment by bpajusco** [comment]
I've submitted changes via git commit on master 5ab7a66 but failed to open a pull request as I can't find the right branches to compare. I'm not the most proficient git hub user but I can certainly do so if directed how to open the request

**Comment by twiecki** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by bpajusco** [comment]
Thanks! I think I've submitted a pull request

**Comment by georgh0021** [comment]
PR #383 was closed at request of @bpajusco. Closing this issue as well.
