### ISSUE TITLE
Help me create "Cumulative Returns" chart.

### ISSUE THREAD

**Issue by webdev522** [quantopian/pyfolio#384]
Dear Sir.

I am a developer from Japan.
I am very interested in your pyfolio repository.

I'd like to create "Cumulative Returns" chart but I have a difficult to understand your whole code.
Which file contains algorithm for "Cumulative Returns" and Bayesian cone.
I have data for the chart on my local machine.

Looking forward to your quick reply.

Best Regards,
Your follower.

**Comment by twiecki** [comment]
https://github.com/quantopian/empyrical/blob/master/empyrical/stats.py#L103 and https://github.com/quantopian/pyfolio/blob/master/pyfolio/bayesian.py#L614
