### ISSUE TITLE
Replaced Yahoo with Google as datasource but no example notebooks run

### ISSUE THREAD

**Issue by dartdog** [quantopian/pyfolio#392]
I am on py3.6, np 1.13, Pandas 20.2 pandas-datareader 0.4.0
I installed this patch which seems to be fine for getting data from Google: https://github.com/quantopian/pyfolio/pull/386/commits/bfdfd3357008f783a2f82279ed544631cc515af2

The best example notebook I could get running seems to be the "Bayesian" notebook, It mostly runs, I do get this error in cell 4 but it does produce some charts and subsequent cells run.
I have not tried zipline :-(
/home/tom/anaconda3/envs/py36n/lib/python3.6/site-packages/numpy/linalg/linalg.py in lstsq(a, b, rcond)
   1955         work = zeros((lwork,), t)
   1956         results = lapack_routine(m, n, n_rhs, a, m, bstar, ldb, s, rcond,
-> 1957                                  0, work, lwork, iwork, 0)
   1958     if results['info'] > 0:
   1959         raise LinAlgError('SVD did not converge in Linear Least Squares')

ValueError: On entry to DLASCL parameter number 4 had an illegal value 

I also reported separately the singe stock tearsheet example gets:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-a429b56b5857> in <module>()
----> 1 pf.create_full_tear_sheet(returns, positions, transactions, slippage=0)

NameError: name 'returns' is not defined

**Comment by volkan** [comment]
Hi @dartdog this patch (https://github.com/quantopian/pyfolio/commit/bfdfd3357008f783a2f82279ed544631cc515af2) doesn't work exactly;

pyfolio/timeseries.py 
```
return empyrical.information_ratio(returns, factor_returns)
```

I am getting this error.
```
AttributeError: 'module' object has no attribute 'information_ratio'
```

**Comment by dartdog** [comment]
see my discussion in empyrical there is a pyfolio patch..in master

**Comment by twiecki** [comment]
Should be fixed on master.
