### ISSUE TITLE
module 'empyrical' has no attribute 'information_ratio'

### ISSUE THREAD

**Issue by yehoshuadimarsky** [quantopian/pyfolio#393]
When calling pyfolio.create_returns_tear_sheet(), I get this AttributeError:
> module 'empyrical' has no attribute 'information_ratio'

Here's my config:
- Python 3.6.1
- Anaconda 4.4
- Microsoft Windows [Version 10.0.14393]
- latest pyfolio, just installed today
- empyrical 0.3.0 (from pip)

I looked at the source code of empyrical, can't find a module or actually anything called 'information_ratio.' Closest I could find is in the docstring for the Sharpe ratio mentioning it's a simplified version of information ratio.
**Looks like a big bug, as create_returns_tear_sheet() is a core function in pyfolio. Please advise.**

**Comment by gusgordon** [comment]
Hi, thanks for the report. Can you try downgrading to empyrical 0.2.2 (`pip install empyrical==0.2.2`)? Pyfolio as a whole is buggy right now, since we are waiting for `pandas_datareader` to get fixed.

**Comment by yehoshuadimarsky** [comment]
Worked, thanks.

**Comment by jonathanng** [comment]
This is still an issue with the latest empyrical.

**Comment by majeedus** [comment]
Using empyrical 0.4.3 and still getting this issue.

**Comment by sokol11** [comment]
0.5.3 still an issue

**Comment by richafrank** [comment]
Hi @sokol11 , `information_ratio` was removed from empyrical and then from [pyfolio in v0.8.0](https://github.com/quantopian/pyfolio/commit/a34222e6a065b85147e9e7e53cce4549058bd51e) (released Aug 23, 2017). It sounds like you have an old version of pyfolio that still depends on `information_ratio`.
