### ISSUE TITLE
Tearsheets on top of each other

### ISSUE THREAD

**Issue by Mustahsen** [quantopian/pyfolio#394]
Hi,

When I run the single stock example I got a tearsheet like this:

![capture](https://user-images.githubusercontent.com/13386316/27641941-a68a586e-5c1d-11e7-8e78-7bdcb5de7145.PNG)

How can I solve this issue ?

**Comment by georgh0021** [comment]
That a bit odd. How are you running pyfolio, and what version of matplotlib are you on?

**Comment by georgh0021** [comment]
@Mustahsen Sounds like you've fixed your problem? Closing this issue now.
