### ISSUE TITLE
Yahoo API not working. 

### ISSUE THREAD

**Issue by apollo06** [quantopian/pyfolio#396]
ConnectionError: HTTPConnectionPool(host='ichart.finance.yahoo.com', port=80): Max retries exceeded with url: /table.csv?ignore=.csv&f=2017&e=28&a=0&g=d&s=FB&b=1&d=5&c=1970 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x114c53198>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by twiecki** [comment]
There is a fix here #395.

**Comment by twiecki** [comment]
Should be fixed on master.
