### ISSUE TITLE
ran tear sheet on Panda dataframe - KeyError: "['Adj Close'] not in index"

### ISSUE THREAD

**Issue by MichJim** [quantopian/pyfolio#404]
ran the tear sheet in Pyfolio in Ipython

Created a data frame including

Date - 10 minutes data
Index - price
Returns - returns of the price index

I do not have an adjusted close in my data index...I got this error message when I ran the tear sheet, concluding remark was "Adj close not in index"

I thought it may be my issue with yahoo, so ran $ pip install yahoo finance

but I got the same error

Do I need to then import Yahoo finance into IPython to get this to work?

KeyError                                  Traceback (most recent call last)
<ipython-input-81-506ca201c686> in <module>()
----> 1 pf.tears.create_returns_tear_sheet(returns_data)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyfolio/plotting.py in call_w_context(*args, **kwargs)
     54         if set_context:
     55             with context():
---> 56                 return func(*args, **kwargs)
     57         else:
     58             return func(*args, **kwargs)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyfolio/tears.py in create_returns_tear_sheet(returns, positions, live_start_date, cone_std, benchmark_rets, bootstrap, return_fig)
    254 
    255     if benchmark_rets is None:
--> 256         benchmark_rets = utils.get_symbol_rets('SPY')
    257         # If the strategy's history is longer than the benchmark's, limit
    258         # strategy

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyfolio/utils.py in get_symbol_rets(symbol, start, end)
    502     return SETTINGS['returns_func'](symbol,
    503                                     start=start,
--> 504                                     end=end)
    505 
    506 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyfolio/utils.py in default_returns_func(symbol, start, end)
    281                                   symbol='SPY',
    282                                   start='1/1/1970',
--> 283                                   end=datetime.now())
    284         rets = rets[start:end]
    285     else:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyfolio/utils.py in get_returns_cached(filepath, update_func, latest_dt, **kwargs)
    191 
    192     if update_cache:
--> 193         returns = update_func(**kwargs)
    194         try:
    195             ensure_directory(cache_dir())

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyfolio/utils.py in get_symbol_from_yahoo(symbol, start, end)
    237 
    238     px = web.get_data_yahoo(symbol, start=start, end=end)
--> 239     rets = px[['Adj Close']].pct_change().dropna()
    240     rets.index = rets.index.tz_localize("UTC")
    241     rets.columns = [symbol]

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   1956                                                              index=self.index,
   1957                                                              name=label,
-> 1958                                                              fastpath=True)
   1959 
   1960                 # this is a cached value, mark it so

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py in _getitem_array(self, key)
   2000         """ return the actual column """
   2001 
-> 2002         # get column
   2003         if self.columns.is_unique:
   2004             return self._get_item_cache(key)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexing.py in _convert_to_indexer(self, obj, axis, is_setter)
   1229         tup[0] = loc
   1230         return tuple(tup)
-> 1231 
   1232     def _get_slice_axis(self, slice_obj, axis=0):
   1233         obj = self.obj

KeyError: "['Adj Close'] not in index"

**Comment by samwincott** [comment]
Using yahoo finance at all won't work I believe, as they no longer provide financial information.

**Comment by georgh0021** [comment]
@MichJim are you using the latest version of pyfolio? There was some issues with Yahoo finance a few weeks ago that have now been fixed. We now pull data from Google if Yahoo finance fails.

https://github.com/quantopian/pyfolio/blob/f0e8afc3b2f505ab03637547223cf86c22c8eedb/pyfolio/utils.py#L250

**Comment by MichJim** [comment]
Thanks - i started using it this week.  I will check.

**Comment by georgh0021** [comment]
@MichJim Sounds like you've resolved your problem! Closing this issue now.

**Comment by MichJim** [comment]
:-) thanks... 

I handed in 3 projects and came on holiday ... sorry left it open. Was frenetic

**Comment by georgh0021** [comment]
Not at all, that's my job! Enjoy your holiday!
