### ISSUE TITLE
Update package on quantopian channel for anaconda

### ISSUE THREAD

**Issue by alen12345** [quantopian/pyfolio#412]
The package is still on version 0.5.1, which forces the use of pip in anaconda.

Please consider updating as for zipline, thank you.

AN

**Comment by twiecki** [comment]
CC @richafrank

**Comment by alen12345** [comment]
@twiecki @richafrank any update on this?

**Comment by twiecki** [comment]
@alen12345 Ideally we'd have the package on conda-forge. Are you familiar with that? It shouldn't be too hard to create a package there and your help would be much appreciated.

**Comment by alen12345** [comment]
@twiecki for sure glad to help! But isn't quantopian using their own channel for anaconda?

https://anaconda.org/search?q=zipline

at the moment conda-forge is not being used.

**Comment by twiecki** [comment]
Yes but that's mostly because we started doing that before conda-forge was around. I would prefer if everything was moved to conda-forge which has a much more comprehensive build system. For alphalens and pyfolio that should be pretty trivial.

**Comment by alen12345** [comment]
Alright, so I will prepare the package for conda-forge in the next days, and let you know about the progress!

**Comment by twiecki** [comment]
Thanks so much for your help!

**Comment by richafrank** [comment]
That's great! 

For zipline, a benefit of the current system that I didn't want to lose with conda-forge is continuous integration. Last time I looked, we wouldn't find out if a PR submitted to zipline breaks the conda packaging until the next zipline release. I don't know if that's still the case, or if perhaps I was just mistaken.

Also, that's not to say we couldn't use conda-forge in addition.

**Comment by alen12345** [comment]
@richafrank I can also have a look at that later on this week and see if we can integrate CI in conda-forge too!

**Comment by richafrank** [comment]
Thanks @alen12345 ! Let us know what you find.

**Comment by alen12345** [comment]
We first need to push empyrical to conda-forge since all dependencies need to be already in the ecosystem. I will work on that too ;)

**Comment by alen12345** [comment]
empyrical has passed all test on conda-forged; I am waiting for the official merge and upload on the channel to go on with pyfolio.

**Comment by alen12345** [comment]
empyrical is on conda-forge! We should also have pyfolio there soon!

**Comment by twiecki** [comment]
Yay!

**Comment by alen12345** [comment]
pyfolio has passed all checks just now!

apart from zipline, which are the other packages you want me add? I would ideally want all the packages from Quantopian to be on conda-forge.

Let me know!

**Comment by alen12345** [comment]
@twiecki please also see PR #518 ; we shoud add the license file to the distributed source code.

**Comment by twiecki** [comment]
alphalens would be great!

**Comment by alen12345** [comment]
@twiecki tests passed for alphalens too, should be merged soon ;)

**Comment by alen12345** [comment]
@twiecki I will look into zipline in the next days too :)

**Comment by alen12345** [comment]
pyfolio has been successfully merged and is now available on conda-forge! I am pushing also qgrid at the moment, and will be finalizing zipline next week.

We can finally close this!

**Comment by twiecki** [comment]
Great -- thanks a bunch, this is a great contribution!
