### ISSUE TITLE
mktime in windows

### ISSUE THREAD

**Issue by dalamar66** [quantopian/pyfolio#413]
Using pyfolio 0.7.0 via anaconda - python 3.5 - pandas-0.20.3

Code:

```
import pyfolio as pf

pf.create_full_tear_sheet(
    returns,
    positions=positions,
    transactions=transactions,
    live_start_date='2005-05-01',
    round_trips=True)
```

Error:

`\lib\site-packages\pyfolio\tears.py in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, set_context)
    149 
    150     if benchmark_rets is None:
--> 151         benchmark_rets = utils.get_symbol_rets('SPY')
    152 
    153     if (unadjusted_returns is None) and (slippage is not None) and\

\lib\site-packages\pyfolio\utils.py in get_symbol_rets(symbol, start, end)
    502     return SETTINGS['returns_func'](symbol,
    503                                     start=start,
--> 504                                     end=end)
    505 
    506 

\lib\site-packages\pyfolio\utils.py in default_returns_func(symbol, start, end)
    281                                   symbol='SPY',
    282                                   start='1/1/1970',
--> 283                                   end=datetime.now())
    284         rets = rets[start:end]
    285     else:

\lib\site-packages\pyfolio\utils.py in get_returns_cached(filepath, update_func, latest_dt, **kwargs)
    191 
    192     if update_cache:
--> 193         returns = update_func(**kwargs)
    194         try:
    195             ensure_directory(cache_dir())

\lib\site-packages\pyfolio\utils.py in get_symbol_from_yahoo(symbol, start, end)
    236     """
    237 
--> 238     px = web.get_data_yahoo(symbol, start=start, end=end)
    239     rets = px[['Adj Close']].pct_change().dropna()
    240     rets.index = rets.index.tz_localize("UTC")

\lib\site-packages\pandas_datareader\data.py in get_data_yahoo(*args, **kwargs)
     38 
     39 def get_data_yahoo(*args, **kwargs):
---> 40     return YahooDailyReader(*args, **kwargs).read()
     41 
     42 

\lib\site-packages\pandas_datareader\yahoo\daily.py in read(self)
    113         """ read one data from specified URL """
    114         try:
--> 115             df = super(YahooDailyReader, self).read()
    116             if self.ret_index:
    117                 df['Ret_Index'] = _calc_return_index(df['Adj Close'])

\lib\site-packages\pandas_datareader\base.py in read(self)
    179         if isinstance(self.symbols, (compat.string_types, int)):
    180             df = self._read_one_data(self.url,
--> 181                                      params=self._get_params(self.symbols))
    182         # Or multiple symbols, (e.g., ['GOOG', 'AAPL', 'MSFT'])
    183         elif isinstance(self.symbols, DataFrame):

\lib\site-packages\pandas_datareader\yahoo\daily.py in _get_params(self, symbol)
     97 
     98     def _get_params(self, symbol):
---> 99         unix_start = int(time.mktime(self.start.timetuple()))
    100         day_end = self.end.replace(hour=23, minute=59, second=59)
    101         unix_end = int(time.mktime(day_end.timetuple()))

OverflowError: mktime argument out of range`

Looks like is related to Windows:

See: https://github.com/mission-liao/pyswagger/issues/63

**Comment by georgh0021** [comment]
Hi @dalamar, are you using the latest version of pyfolio? There was an issue with Yahoo and pandas data reader in pyfolio 0.7.0 that has since been patched.
