### ISSUE TITLE
Standardize style (axis, legend, labels, capitalization, ...) across all plots

### ISSUE THREAD

**Issue by gusgordon** [quantopian/pyfolio#415]
Currently, pyfolio is a jumble of styles. Different plots have different looking legends, some plots don't have their labels capitalized, etc. Some differing style is obviously fine, but we should adopt a basic standard that is used in new plots.

I don't think this will too much effort — the bulk is just standardizing the legends, I believe. I'm not sure if breaking out some `style_plot` function is the answer, because there will be small differences between plots.

Things I can think of:
- Capitalize plot titles/legends/axis labels correctly
- Ensure proper rotation of axis labels
- Standardize legend style (I'm personally a fan of the transparent background-box)
- Standardize font sizes (might already be done)

**Comment by georgh0021** [comment]
Also, while we're at it: 
- Ensure that colors are differentiable (see #256)
