### ISSUE TITLE
Yahoo problem for Pyfolio usage

### ISSUE THREAD

**Issue by davins90** [quantopian/pyfolio#435]
Hi all,
i'm new on this community. I'm trying to use pyfolio packcage but when i run this parte of the code:
"stock_rets = pf.utils.get_symbol_rets('FB')"
i get that problem:
"ConnectionError: HTTPConnectionPool(host='ichart.finance.yahoo.com', port=80): Max retries exceeded with url: /table.csv?s=AGG&a=0&b=1&c=1970&d=7&e=29&f=2017&g=d&ignore=.csv (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000002384CC7D588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))"

It seems that it's not possible to dowload the data from yahoo. Is there any solutions?
thaks all very much,

Daniele

**Comment by twiecki** [comment]
Can you update to master with:
`pip install -U --no-deps git+https://github.com/quantopian/pyfolio` and see if the problem persists?

**Comment by davins90** [comment]
hello,

thanks for your answer. Now there is a problem that gives the following error:

"mktime argument out of range"

thanks very much

I really would like to use pyfolio, but nothing seems works on my pc!

**Comment by acaforio** [comment]
same for me...
same error....
I'm just trying to run the single stock example here:
https://quantopian.github.io/pyfolio/notebooks/single_stock_example/

and I stop at the first action:

stock_rets = pf.utils.get_symbol_rets('FB')

...
D:\Anaconda\lib\site-packages\pandas_datareader\yahoo\daily.py in _get_params(self, symbol)
     97 
     98     def _get_params(self, symbol):
---> 99         unix_start = int(time.mktime(self.start.timetuple()))
    100         day_end = self.end.replace(hour=23, minute=59, second=59)
    101         unix_end = int(time.mktime(day_end.timetuple()))

OverflowError: mktime argument out of range

**Comment by jaycode** [comment]
I updated `get_symbol_returns_from_yahoo` function from empyrical plugin and that has corrected this issue. This was caused by a change in csv headers from Yahoo.

**Comment by jaycode** [comment]
I decided to leave Yahoo API altogether and went with Quandl API. This update does not require any changes to the modules; I describe it in more detail in [this article](http://teguhwijaya.com/pyfolio-single-stock-example.html)

Basically, add the following code before running `pf.utils.get_symbol_rets`:

```
from empyrical.utils import get_utc_timestamp, get_returns_cached, _1_bday_ago, data_path
from pandas_datareader import data as web
from datetime import datetime
import pandas as pd

def get_symbol_returns_from_quandl(symbol, start=None, end=None):
    """
    Wrapper for pandas.io.data.get_data_quandl().
    Retrieves prices for symbol from quandl and computes returns
    based on adjusted closing prices.

    Parameters
    ----------
    symbol : str
        Symbol name to load, e.g. 'SPY'
    start : pandas.Timestamp compatible, optional
        Start date of time period to retrieve
    end : pandas.Timestamp compatible, optional
        End date of time period to retrieve

    Returns
    -------
    pandas.DataFrame
        Returns of symbol in requested period.
    """

    px = web.get_data_quandl(symbol, start=start, end=end)
    rets = px[['AdjClose']]
    rets = rets.shift(-1)
    rets.iloc[-1]['AdjClose'] = px.tail(1)['AdjOpen']
    rets = rets.shift(1) / rets - 1
    rets = rets.dropna()
    rets.index = rets.index.to_datetime()
    rets.index = rets.index.tz_localize("UTC")
    rets.columns = [symbol]
    return rets

def returns_func(symbol, start=None, end=None):
    """
    Gets returns for a symbol.
    Queries Quandl Finance. Attempts to cache SPY.

    Parameters
    ----------
    symbol : str
        Ticker symbol, e.g. APPL.
    start : date, optional
        Earliest date to fetch data for.
        Defaults to earliest date available.
    end : date, optional
        Latest date to fetch data for.
        Defaults to latest date available.

    Returns
    -------
    pd.Series
        Daily returns for the symbol.
         - See full explanation in tears.create_full_tear_sheet (returns).
    """

    if start is None:
        start = '1/1/1970'
    if end is None:
        end = _1_bday_ago()

    start = get_utc_timestamp(start)
    end = get_utc_timestamp(end)

    if symbol == 'SPY':
        filepath = data_path('spy.csv')
        rets = get_returns_cached(filepath,
                                  get_symbol_returns_from_quandl,
                                  end,
                                  symbol='SPY',
                                  start=start,
                                  end=datetime.now())
        
        try:
            rets = rets[rets.index.isin(pd.bdate_range(start, end))]
        except Exception as e:
            rets = rets[start:end]
    else:
        rets = get_symbol_returns_from_quandl(symbol, start=start, end=end)
    rets.sort_index(inplace=True)
    return rets[symbol]

pf.utils.register_return_func(returns_func)
```
Now tell me, would you like me to update pyfolio module to use Quandl by default?

**Comment by nemozny** [comment]
@jaycode Yes please!

**Comment by jaycode** [comment]
@nemozny I am about to go to bed now so expect a longer wait before my next reply.

The change has been incorporated into pyfolio, but just a few days ago Quandl no longer give away their WIKI/SPY data for free. I am not quite sure where else we can get historical SPY data from.

**Comment by nemozny** [comment]
@jaycode Yes, I noticed the same yesterday, as I tried to replace benchmark_rets from your script above. I don't know where to get the SPY, in this state of things. 
When you backtest 1960+, all free data sources are  of extremely poor quality. Including Quandl WIKIP, which is in fact just stolen Yahoo.
I found morningstar is the only "free" reliable source, but they make hard to obtain the data.
http://globalquote.morningstar.com/globalcomponent/RealtimeHistoricalStockData.ashx?ticker=SPY&showVol=true&dtype=his&f=d&curry=USD&isD=true&isS=true&hasF=true&ProdCode=DIRECT
