### ISSUE TITLE
performance attribution does not work correctly when percentages are passed in

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#439]
We need a flag that says whether `positions` are in $ or %. Calling `get_perc_alloc()` on % does not work.

**Comment by vikram-narayan** [comment]
@twiecki what do you think about making `get_percent_alloc` return the input as is, if the input is already in %?

**Comment by twiecki** [comment]
Question is if we can detect that reliably.

**Comment by vikram-narayan** [comment]
ah gotcha. I'll add a flag which does that, and defaults to dollars

**Comment by vikram-narayan** [comment]
added this flag to to the risk exposure plot PR: #433
