### ISSUE TITLE
pull Fama-French risk factors directly from the academic website

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#44]
We should look into directly pulling this data since the csv can get out of date really quickly.  Maybe we supply a default csv (if we can) as well as expose a function to pull the data from the university page

We also might want to confirm if there are any licenses or issues with redistributing it. @twiecki maybe you have some experience understanding redistribution of data in the OSS world?

**Comment by gusgordon** [comment]
Dartmouth page is down right now. Quandl seems more reliable, but we could have a double fallback i.e. dartmouth -> quandl -> local

**Comment by gusgordon** [comment]
Dartmouth seems to be up at your second link here: http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html

I think the pandas function and old URL are broken, but we can unzip files with python so shouldn't be a problem.

I can't seem to find UMD anywhere. @justin @humdings anyone know where that's from?

**Comment by gusgordon** [comment]
From justin, UMD = momentum factors -> http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/F-F_Momentum_Factor_daily_CSV.zip
