### ISSUE TITLE
Yahoo failure message

### ISSUE THREAD

**Issue by riabaldevia** [quantopian/pyfolio#478]
Are there plans to replace Yahoo Finance?

> Yahoo Finance read failed: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/WTW?period1=18000&period2=1510117199&interval=1d&events=history&crumb=Rk%5Cu002F%5Cu002FWh31Afe, falling back to Google
  UserWarning

**Comment by twiecki** [comment]
@riabaldevia It should already fall back to google, is it not working?

**Comment by riabaldevia** [comment]
@twiecki it works. Initially right before running  print(stock_returns) it would give me the warning and wondering if there will be changes to get rid of the yahoo api call and just go to google by default so that that user warning will no longer appear. thank you.
