### ISSUE TITLE
Google SPY returns reach back too short causing tear-sheet to cut off returns

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#484]
Yahoo used to provide SPY returns back until 1970 but they stopped their API. Thus, we fall back to google which only provides a fixed window of about 1 year. This causes a problem in the tear-sheets where we cut off any returns that have no SPY coverage (https://github.com/quantopian/pyfolio/blob/master/pyfolio/tears.py#L341 and again https://github.com/quantopian/pyfolio/blob/master/pyfolio/tears.py#L352 which is actually a duplicate), which is now very little. We need to be robust to this or find a better source for spy going back further in time.

**Comment by SteffenNa** [comment]
You might want to look at [alphavantage](https://www.alphavantage.co) as an alternative data source. Requires a free API key but the data is much better quality than yahoo or google.
