### ISSUE TITLE
Bayesian Tear Sheet fails in Research

### ISSUE THREAD

**Issue by mmargenot** [quantopian/pyfolio#498]
Calling a Bayesian Tear Sheet fails with `AssertionError: axis must be between 0 and 1, input was columns`. I'm pretty sure it's due to https://github.com/quantopian/pyfolio/blob/master/pyfolio/bayesian.py#L68.

**Comment by jaycode** [comment]
I got the same error.

**Comment by twiecki** [comment]
Closed by https://github.com/quantopian/pyfolio/pull/508.
