### ISSUE TITLE
Incorrect Legend for HML in Rolling Fama French Plot

### ISSUE THREAD

**Issue by MichaelJMath** [quantopian/pyfolio#499]
It looks like the HML legend label is incorrect in the `plotting.plot_rolling_fama_french()` function. It currently labels the HML factor as "High Growth". However, this is actually the opposite of what it should be as HML stands for High Book-to-Market minus Low Book-to-Market, in other words, value minus growth. Source: http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/Data_Library/f-f_factors.html

https://github.com/quantopian/pyfolio/blob/3909c49c3875d1be7700f9a7f4c4da60eb957d4c/pyfolio/plotting.py#L196-L199

Maybe the label should simply be "Value (HML)".

**Comment by twiecki** [comment]
Yes, that seems right. Want to do a PR?
