### ISSUE TITLE
*** SystemError: <class 'str'> returned a result with an error set

### ISSUE THREAD

**Issue by wilsonwang371** [quantopian/pyfolio#500]
https://github.com/quantopian/pyfolio/blob/3909c49c3875d1be7700f9a7f4c4da60eb957d4c/pyfolio/timeseries.py#L899

*** SystemError: <class 'str'> returned a result with an error set

error when running on

python 3.6.3
pandas 0.18.1

**Comment by eigenfoo** [comment]
Hm, sounds related to [this known issue on pandas](https://stackoverflow.com/questions/42595429/how-to-convert-pd-series-to-datetime#42600828).

Could you try upgrading pandas to 0.19 or higher and see if that works?

**Comment by wilsonwang371** [comment]
I suggest making some change to these lines so that they can be more compatible with different pandas versions.

I actually forgot about my comment. When I was trying to use pyfolio one week before on a different machine, I saw the same issue and guess what, my comment here helped me out.

**Comment by twiecki** [comment]
do you have a fix? happy to review a PR.

**Comment by eigenfoo** [comment]
@twiecki looks like it's #502, which has been sitting there for a while. @wilsonwang371 is that correct?

**Comment by wilsonwang371** [comment]
@eigenfoo yes. let me take a look at the root cause and explain it here later.

**Comment by wilsonwang371** [comment]
not hitting this error anymore. I guess is it a corner case in one of my previous code. anyway. I am closing this now
