### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by luca-s** [quantopian/pyfolio#503]
I believe the `Figures` created in the tear sheet functions should be closed when `return_fig` is `False` otherwise a memory leak is created.

From matplotlib documentation:

The memory required for a Figure is not completely released until the figure is explicitly closed with close(). Deleting all references to the figure, and/or using the window manager to kill the window in which the figure appears on the screen, is not enough, because pyplot maintains internal references until close() is called.

**Comment by twiecki** [comment]
Would they still be displayed in the NB?

**Comment by luca-s** [comment]
If the `Figure` is closed after being shown it will be displayed in the NB. As pyfolio calls `plt.show()` at the end of its tears.* functions it would be possible to close the `Figures` after that statement.

**Comment by twiecki** [comment]
OK, thanks. Want to submit a PR?

**Comment by luca-s** [comment]
Sure

**Comment by twiecki** [comment]
Closed by #504.
