### ISSUE TITLE
Docs at https://quantopian.github.io/pyfolio/ from an older release

### ISSUE THREAD

**Issue by appletonwebb** [quantopian/pyfolio#511]
Docs at https://quantopian.github.io/pyfolio/ seem to be from an older release. The latest release listed here is 0.6, https://quantopian.github.io/pyfolio/whatsnew/.

**Comment by twiecki** [comment]
Thanks for the report, should be updated.

**Comment by appletonwebb** [comment]
Indeed, thank you 👍
