### ISSUE TITLE
pyfolio uses old pymc3 API

### ISSUE THREAD

**Issue by LorenzG** [quantopian/pyfolio#512]
Hello,

I'm trying to run some examples but I'm having all sort of problems with the dependencies (theano, pymc3). Also, whenever I update a dependency, it requires upgrading/downgrading others, so I feel like I ended up in an infinite loop.

I'm using the latest Anaconda on windows.

Can you please specify the versions of the major dependencies you are using, please?

thanks
Lorenzo

**Comment by twiecki** [comment]
Can you give a few more details on which versions conflict with what exactly?

**Comment by LorenzG** [comment]
Hi @twiecki 
Sorry for the late response.

For instance, I'm running bayesian.ipynb, and I'm getting this error message.

![image](https://user-images.githubusercontent.com/7131055/35780663-c5436996-09d6-11e8-8551-7565e605309f.png)

Do you know what this is about?

**Comment by twiecki** [comment]
Looks like a pyfolio bug (pymc3 changed the API a bit).

**Comment by twiecki** [comment]
In the interim, you could try installing pymc 3.1.

**Comment by twiecki** [comment]
Actually the current code does not reference this. Can you try pyfolio master via `pip install -U --no-deps git+https://github.com/quantopian/pyfolio`?
