### ISSUE TITLE
Missing Stock Split for XLF on 09/19/2016 in backtesting

### ISSUE THREAD

**Issue by rapetter94** [quantopian/pyfolio#519]
XLF underwent the following corp. action on 09/19/2016:
a 1231 for 1000 split, meaning for each 1000 shares of XLF owned pre-split, the shareholder now owned 1231 shares.

Confirmed here: https://www.stocksplithistory.com/?symbol=XLF

The pricing data IS adjusted in research, but not in backtesting.

Screenshot in research (where pricing data IS adjusted):
![image](https://user-images.githubusercontent.com/31143725/36571244-ba208b94-1803-11e8-9ed1-07bf475e656b.png)

Backtesting (where it is NOT adjusted):
![image](https://user-images.githubusercontent.com/31143725/36571406-80c3499e-1804-11e8-91e8-7a886cafd1c2.png)

**Comment by twiecki** [comment]
@rapetter94 I don't think this is a pyfolio issue, open in qexec?
