### ISSUE TITLE
yahoo / google problem

### ISSUE THREAD

**Issue by aseedb** [quantopian/pyfolio#525]
I am new to pyfolio. Do I need to install an old version of pandas? 
First I am getting a deprecation error
`ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues`

Then while handling this exception, a RemoteDataError is raised. Obviously panda/pyfolio tries to download the data from google finance but that fails.
`RemoteDataError: Unable to read URL: https://finance.google.com/finance/historical?q=FB&startdate=Jan+01%2C+1970&enddate=Mar+27%2C+2018&output=csv`

**Comment by nemozny** [comment]
I am experiencing the same error. You guys are trying to download data from Google and he says

> We're sorry...
> ... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

Is there some workaround? How can I switch to a different data source?

**Comment by Dan733** [comment]
Same issue. Currently cannot run a full tearsheet in pyfolio. Does anyone know how to format a custom benchmark to use with `benchmark_rets`?

**Comment by nemozny** [comment]
@Dan733 You have to download your own index and calculate the returns. The format should be the same as in strategy returns.
>date	SPX
>1928-01-04	-0.04

**Comment by AliAskari** [comment]
@nemozny Would you mind explaining more how this should be done?

Do you mean I should also run my strategy on SPX and find the returns of my strat on SPX?

**Comment by h55nick** [comment]
Here is a gist of what I've done to get the working locally (apologizes if it doesn't work as is, copy and pasted from a larger file for brevity)

https://gist.github.com/h55nick/2fa8e9dd71646728565ece4899dd70e1

think the bigger deal here is waiting on master zipline to have the PD upgrade branch merged in so that we can move this to using pd-datareader? The collision between the deps causes some problems.

Hope this helps. Trying to start contributing more!

**Comment by twiecki** [comment]
Thanks @h55nick, want to do a PR?

**Comment by h55nick** [comment]
This PR should do the trick once merged and then bumping the emp dep.

https://github.com/quantopian/empyrical/pull/89

The number of deps in the util.py is slightly worrisome.

**Comment by twiecki** [comment]
I think this is what we should do: https://github.com/quantopian/pyfolio/issues/534

**Comment by nemozny** [comment]
@twiecki Having user supplying own benchmark_rets just raises its own issues, as at first I had "not monotonic increasing" error, while both returns and benchmark_rets were monotonic increasing. I tested with returns.is_monotonic_increasing.
However pyfolio or some dependency probably does some join of these timeseries?
Now I supplied different returns dataframe and my current error is ValueError: Found input variables with inconsistent numbers of samples: [127, 130]. I gave up then.
So yes, you can make benchmark_rets users problem, but make the create_tearsheet function foolproof.
