### ISSUE TITLE
Using pyfolio independently

### ISSUE THREAD

**Issue by JordanPlatts** [quantopian/pyfolio#529]
I ran into the issue below just trying to analyze returns. While I saw that there is another issue talking about working around the data issues, I wonder if you can use pyfolio as a stand alone package from zipline(and from data providers)?

If so, are there examples of using pyfolio to analyze returns/transactions/positions not from zipline?

    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
    import pyfolio as pf
    names = ['foo','bar']
    dates = pd.date_range(start='2017-01-01',end='2017-12-31', freq=pd.tseries.offsets.BDay())
    n = len(dates)
    rdf = pd.DataFrame(
        np.zeros((n, len(names))),
        index = dates,
        columns = names
    )
    
    np.random.seed(1)
    rdf['foo'] = np.random.normal(loc = 0.1/n,scale=0.2/np.sqrt(n),size=n)
    rdf['bar'] = np.random.normal(loc = 0.04/n,scale=0.05/np.sqrt(n),size=n)
    
    pdf = 100*np.cumprod(1+rdf)
    pdf.plot()
    pdf.head()
    
    pf.create_returns_tear_sheet(rdf['foo'])

Trying the code above throws the error below

RemoteDataError: Unable to read URL: https://finance.google.com/finance/historical?q=SPY&startdate=Jan+01%2C+1970&enddate=Apr+17%2C+2018&output=csv
Response Text:
b'<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We\'re sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can\'t process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>'

**Comment by AliAskari** [comment]
@JordanPlatts Have you had any success in getting around this issue?

**Comment by JordanPlatts** [comment]
To be honest, I haven't tried again. 

I posted this because I was hoping someone would point me to an example of using pyfolio as a stand-alone package.

**Comment by twiecki** [comment]
I think this is a dup of https://github.com/quantopian/pyfolio/issues/525, which we urgently need to fix.

**Comment by qianmao** [comment]
I tried the example by @JordanPlatts and it works.

**Comment by twiecki** [comment]
Thanks for testing @qianmao!
