### ISSUE TITLE
Fix travis issues

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#530]
CC @richafrank

**Comment by richafrank** [comment]
@twiecki Looks like 2 issues: 

1. The tests are erroring in getting data from google finance.
1. test_beta is failing. Looks like differences between successful and failing builds include the versions of numpy and empyrical...

**Comment by twiecki** [comment]
I would suggest to make the code do beta and fama-french analyses optional, only if the right data is passed in. We can then decide if we want to include SPY returns somehow or just rely on the user having access to them if they want to use them.

**Comment by richafrank** [comment]
For the second issue: https://github.com/quantopian/pyfolio/pull/531

**Comment by twiecki** [comment]
Should be fixed by #536.
