### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by AliAskari** [quantopian/pyfolio#532]
I have tried to follow up on documents and online tutorials but I cannot seem to make `pyfolio` generate the tear sheats.

Steps to reproduce following [this](https://github.com/quantopian/pyfolio/blob/0ea262f93251f015d70c694d0bd18654bddd7df2/pyfolio/examples/single_stock_example.ipynb) tutorial:

- After trying to fetch the daily returns for any stock, `FB` in the example, 

      stock_rets = pf.utils.get_symbol_rets('FB')

I keep getting the following error from `pandas_datareader`:

    pandas_datareader._utils.RemoteDataError: Unable to read URL: https://finance.google.com/finance/historical?q=FB&startdate=Jan+01%2C+1970&enddate=May+09%2C+2018&output=csv

How can I avoid getting this error or use some locally available data? What should be the format of that data?

**Comment by twiecki** [comment]
Thanks, this is related to https://github.com/quantopian/pyfolio/issues/525.
