### ISSUE TITLE
MAINT: make pyfolio independent of SPY or FF

### ISSUE THREAD

**Issue by eigenfoo** [quantopian/pyfolio#534]
Currently pyfolio fetches any benchmarks that you do not supply. These happen to be SPY, and the Fama-French factors.

We should relax this: pyfolio should insist that you enter a benchmark, and a set of risk factors. If you do not, it just won't perform any of the appropriate analyses.

https://github.com/quantopian/pyfolio/blob/20060a3045c4176f9a2c417a0cb993b987441885/pyfolio/tears.py#L193-L194

All this means is that lines like these just need to be removed, or raise a `ValueError` to tell the user to decide on a benchmark. Users can use empyrical (e.g. `ep.utils.get_fama_french`) to fetch SPY or FF factors, if they so wish.

This supercedes #495

**Comment by twiecki** [comment]
We shouldn't raise an exception but just skip any analyses that depend on `benchmark` or `fama_french`.

**Comment by eigenfoo** [comment]
Closed by the merged PR.
