### ISSUE TITLE
Bayesian tearsheet problem: TypeError: can't pickle CVM objects

### ISSUE THREAD

**Issue by SteffenNa** [quantopian/pyfolio#547]
Hello
am using pyfolio v0.8.0. My Notebook which previously worked throws an error now. Would appreciate any help. 
```
pf.create_bayesian_tear_sheet(ret.equity, benchmark_rets = ret['60/40'], live_start_date = ret.index[-15])
```
Full traceback:

Running T model
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [nu_minus_two_log__, volatility_log__, mean returns]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/steffen/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py", line 151, in _feed
    obj, reducers=reducers)
  File "/Users/steffen/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 145, in dumps
    p.dump(obj)
TypeError: can't pickle CVM objects
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<timed eval> in <module>()

~/miniconda3/lib/python3.6/site-packages/pyfolio/plotting.py in call_w_context(*args, **kwargs)
     50         if set_context:
     51             with plotting_context(), axes_style():
---> 52                 return func(*args, **kwargs)
     53         else:
     54             return func(*args, **kwargs)

~/miniconda3/lib/python3.6/site-packages/pyfolio/tears.py in create_bayesian_tear_sheet(returns, benchmark_rets, live_start_date, samples, return_fig, stoch_vol)
   1104     trace_t, ppc_t = bayesian.run_model('t', df_train,
   1105                                         returns_test=df_test,
-> 1106                                         samples=samples, ppc=True)
   1107     previous_time = timer("T model", previous_time)
   1108 

~/miniconda3/lib/python3.6/site-packages/pyfolio/bayesian.py in run_model(model, returns_train, returns_test, bmark, samples, ppc)
    566                                                   bmark, samples)
    567     elif model == 't':
--> 568         model, trace = model_returns_t(returns_train, samples)
    569     elif model == 'normal':
    570         model, trace = model_returns_normal(returns_train, samples)

~/miniconda3/lib/python3.6/site-packages/pyfolio/bayesian.py in model_returns_t(data, samples)
    168                          np.sqrt(252))
    169 
--> 170         trace = pm.sample(samples)
    171     return model, trace
    172 

~/miniconda3/lib/python3.6/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, nuts_kwargs, step_kwargs, progressbar, model, random_seed, live_plot, discard_tuned_samples, live_plot_kwargs, compute_convergence_checks, use_mmap, **kwargs)
    440         _print_step_hierarchy(step)
    441         try:
--> 442             trace = _mp_sample(**sample_args)
    443         except pickle.PickleError:
    444             _log.warning("Could not pickle model, sampling singlethreaded.")

~/miniconda3/lib/python3.6/site-packages/pymc3/sampling.py in _mp_sample(**kwargs)
    980         traces = Parallel(n_jobs=cores)(jobs)
    981     else:
--> 982         traces = Parallel(n_jobs=cores, mmap_mode=None)(jobs)
    983 
    984     return MultiTrace(traces)

~/miniconda3/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
    960 
    961             with self._backend.retrieval_context():
--> 962                 self.retrieve()
    963             # Make sure that we get a last message telling us we are done
    964             elapsed_time = time.time() - self._start_time

~/miniconda3/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    863             try:
    864                 if getattr(self._backend, 'supports_timeout', False):
--> 865                     self._output.extend(job.get(timeout=self.timeout))
    866                 else:
    867                     self._output.extend(job.get())

~/miniconda3/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    513         AsyncResults.get from multiprocessing."""
    514         try:
--> 515             return future.result(timeout=timeout)
    516         except LokyTimeoutError:
    517             raise TimeoutError()

~/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/_base.py in result(self, timeout)
    429                 raise CancelledError()
    430             elif self._state == FINISHED:
--> 431                 return self.__get_result()
    432             else:
    433                 raise TimeoutError()

~/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/_base.py in __get_result(self)
    380     def __get_result(self):
    381         if self._exception:
--> 382             raise self._exception
    383         else:
    384             return self._result

~/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/queues.py in _feed(buffer, notempty, send_bytes, writelock, close, reducers, ignore_epipe, onerror, queue_sem)
    149                         # serialize the data before acquiring the lock
    150                         obj = CustomizableLokyPickler.dumps(
--> 151                             obj, reducers=reducers)
    152                         if wacquire is None:
    153                             send_bytes(obj)

~/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py in dumps(cls, obj, reducers, protocol)
    143         buf = io.BytesIO()
    144         p = cls(buf, reducers=reducers, protocol=protocol)
--> 145         p.dump(obj)
    146         if sys.version_info < (3, 3):
    147             return buf.getvalue()

TypeError: can't pickle CVM objects

Regards, Steffen

**Comment by eigenfoo** [comment]
Hi @SteffenNa! Apologies for the late response. Have you checked out [this issue on PyMC3](https://github.com/pymc-devs/pymc3/issues/3068)? It looks like to be what you're describing.

**Comment by SteffenNa** [comment]
Yes i did. same problem.

**Comment by SteffenNa** [comment]
after I did a clean new install on my new MacBook its works. :-)
