### ISSUE TITLE
Error with backtrader and pyfolio

### ISSUE THREAD

**Issue by GabsGear** [quantopian/pyfolio#555]
I'm trying to use pyfolio with backtrader, and i follow this steps:
https://www.backtrader.com/blog/posts/2016-07-17-pyfolio-integration/pyfolio-integration.html

and found this error:
![image](https://user-images.githubusercontent.com/20424895/43563958-d09c3fa6-95fa-11e8-9363-81c2068dc5b2.png)

i remove gross_lev and found this error:

![image](https://user-images.githubusercontent.com/20424895/43564020-13b52212-95fb-11e8-8eda-eeacf5331f16.png)
...

any help?
I use this code for pyfolio:

![image](https://user-images.githubusercontent.com/20424895/43564072-63608234-95fb-11e8-9baf-6032c8551810.png)

**Comment by eigenfoo** [comment]
Hi! Are you on the latest version of `pyfolio` (`v0.9.0`)? #536 removed all pandas-datareader references to Yahoo Finance, Google, etc.

**Comment by GabsGear** [comment]
Oh thanks @eigenfoo its the problem you are correct, the post have this warning:
```
pyfolio APIs have changed and create_full_tear_sheet no longer has a gross_lev as a named argument.

Consequently the sample below doesn’t work
```

I will go find another way to use pyfolio with backtrader.
 Thanks again.
