### ISSUE TITLE
Transaction commission ignored

### ISSUE THREAD

**Issue by eranhirs** [quantopian/pyfolio#558]
Hello pyfolio maintainers team,

I run into several places in the code that ignore the transactions commissions.
I would love to have an option (even if it is not the default) to take commission into account in all calculations.

Here are the places I run into
1. `def make_transaction_frame` ignores `df['commission']` when setting `txn_dollars`
```
    df['txn_dollars'] = -df['amount'] * df['price']
```
2. `def extract_round_trips` ignores `t['commission']` when calculating `pnl`
```
                        pnl += -(price + prev_price)
```

The only place I found referencing `txn['commission']` is `def map_transaction(txn)`

**Comment by eranhirs** [comment]
Specifically `extract_round_trips` is calculating `returns` using the `pnl` without the commission, so it will also require me to re-calculate the `returns`.

Also, it might break when upgrading versions and ideally I prefer the project to support it.

Thanks for the fast response!

**Comment by twiecki** [comment]
What we do internally is to directly adjust returns, positions and transactions to have the prices including slippage and commissions. That offers most flexibility as txn cost modeling can get arbitrarily complex and every implementation in pyfolio will be limited.

**Comment by eranhirs** [comment]
Interesting, is there an existing helper method I can use to combine the commission and slippage with the price?

**Comment by twiecki** [comment]
Nothing that is open sourced, sorry, but it shouldn't be too difficult to replicate that yourself. I'm closing this as I don't think it's a good idea to add that to pyfolio, feel free to keep asking questions.

**Comment by twiecki** [comment]
@eranhirs If you want, a PR noting that in the doc string would be much appreciated.
