### ISSUE TITLE
plot_rolling_sharpe - add benchmark/factor

### ISSUE THREAD

**Issue by jankrepl** [quantopian/pyfolio#561]
Hey all,

I want to suggest an enhancement:

Just as **plot_rolling_volatility** allows for passing benchmark/factor returns it would be nice to allow the same thing for **plot_rolling_sharpe**.

What do you think?

**Comment by eigenfoo** [comment]
@jankrepl good idea! This also fits in with the spirit of #536: we're trying to make pyfolio not assume that you want the SPY benchmark, and allow users to either specify their own benchmark, or else assume that you genuinely prefer no benchmark.

Would you want to whip up a PR?

**Comment by jankrepl** [comment]
Sure!
