### ISSUE TITLE
pyfolio - KeyError: None of DatetimeIndex ... are in the [index], occurred at index SMB

### ISSUE THREAD

**Issue by ashleylamlam** [quantopian/pyfolio#567]
I tried to use pyfolio to generate backtest report by using this

pf.create_full_tear_sheet(returns, benchmark_rets=bm_returns, set_context=True)

but it gives me the error like this:

File "C:\Users\ashley\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1206, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)))
KeyError: ("None of [DatetimeIndex(['2001-01-02', '2001-01-03', '2001-01-04', '2001-01-05',\n               '2001-01-08', '2001-01-09', '2001-01-10', '2001-01-11',\n               '2001-01-12', '2001-01-16',\n               ...\n               '2001-06-20', '2001-06-21', '2001-06-22', '2001-06-25',\n               '2001-06-26', '2001-06-27', '2001-06-28', '2001-06-29',\n               '2001-07-02', '2001-07-03'],\n              dtype='datetime64[ns]', name='date', length=127, freq=None)] are in the [index]", 'occurred at index SMB')

**Comment by cschiri** [comment]
@ashleylamlam I am currently experiencing the same issue. How did you manage to resolve it?

**Comment by cschiri** [comment]
Update: I resolved the issue by simply upgrading to the latest edition of Pyfolio. It had all the bug fixes.
