### ISSUE TITLE
Someone is name squatting

### ISSUE THREAD

**Issue by timkpaine** [quantopian/pyfolio#576]
https://pypi.org/project/pyfolio3/
https://github.com/santosjorge/cufflinks/issues/145

**Comment by timkpaine** [comment]
here's the non-forked repo: 
https://github.com/liudengfeng/pyfolio3

**Comment by timkpaine** [comment]
removed from pypi, will let you guys pursue copyright stuff if desired

**Comment by jikquantopian** [comment]
Project has been removed from Github as well, so copyright changes are no longer an issue.
