### ISSUE TITLE
Cum_returns support cumsum mode?

### ISSUE THREAD

**Issue by huaiweicheng** [quantopian/pyfolio#588]
Hi
I use pyfolio to analyze my returns series. I notice that pyfolio use cum_returns in empyrical to calculate the  
cumulative net worth. However, what I need is to compute the cum returns use a simple addition method.
Which is np.cumsum(returns) instead of  

np.add(returns, 1, out=out)
out.cumprod(axis=0, out=out)
if starting_value == 0:
    np.subtract(out, 1, out=out)

Though I can fix the problem myself, I need to overwrite empyrical cum_returns.
What I wonder is that cound pyfolio/empyrical support this type of returns cum method?

**Comment by twiecki** [comment]
@huaiweicheng Unfortunately I don't think that's a good thing to allow a user to do, thus overwriting or monkey-patching is your best bet here.
