### ISSUE TITLE
create_perf_attrib_tear_sheet not work in Python3

### ISSUE THREAD

**Issue by huaiweicheng** [quantopian/pyfolio#607]
create_perf_attrib_tear_sheet iterate dictionary use iteritems which is not existed in Python3. Hope to fix this bug!

**Comment by twiecki** [comment]
@huaiweicheng Want to do a PR?

**Comment by huaiweicheng** [comment]
@twiecki  I could do this. But I notice there exist two types of iteration (items() & iteritems)all over the code. 
![image](https://user-images.githubusercontent.com/4011117/62852227-66531b80-bd1b-11e9-8723-7fc2b40ccf73.png)
![image](https://user-images.githubusercontent.com/4011117/62852240-710db080-bd1b-11e9-9ebc-a4205b4dd011.png)

As I know, pandas has decided to drop support python series.
（Warning: Starting with the 0.25.x series of releases, pandas only supports Python 3.5.3 and higher. See Plan for dropping Python 2.7 for more details.）

Is that not necessary to support a python2 version of pyfolio considering current suitation?  If so, It is much more easier to do the PR. Just replace all iteritems to items...

**Comment by twiecki** [comment]
I would just replace all those with `.items()` and see how far that gets.

**Comment by huaiweicheng** [comment]
Great! If the replacing is enough i think you can finish in a few minutes. There is no need to create a PR for this.
As we have come to newer Pandas, there is another issue. The create_capacity_tear_sheet & create_risk_tear_sheet of pyfolio use the Panel data structure of Pandas, which is also dropped by Pandas 0.25. 
(Warning Panel has been fully removed. For N-D labeled data structures, please use xarray)

This upgrading may cost much more time to upgrade and I can consider doing the PR.

**Comment by twiecki** [comment]
@huaiweicheng A PR would still be greatly appreciated, please consider it, but no worries if not.

And yes, help replacing panel with multi-indexed dataframe would be awesome.
