### ISSUE TITLE
Add optional parameters to timeseries.portfolio_returns to enable weighting of holdings based on the metric

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#61]
Right now portfolio_returns only supports equal-weight portfolios.  We should enable either the passing in of static custom weights.  E.g. If we pass in 4 stocks, we can also just pass in a list of 4 custom static weights like, [0.5, 0.2, 0.1, 0.2].

Or we can pass in a metric which is first applied to all the input timeseries and dynamically weights each holding based on the rolling metric value. E.g. This would be a general implementation that would enable volatility weighting of the holdings

**Comment by justinlent** [comment]
@twiecki just so i can point you to where I committed an ipynb with some functions where I implemented this, you can find it in this commit in branch 'vol_weighted_portfolio'

the ipynb in /examples is just a simple example with some notes/comments explaining how I implemented the weighting functions in a general weight, of which volatility-weighting is accomplished by passing in np.std as the weighting function. Just let me know if you have any questions, or if you think there is a weight to improve it.

https://github.com/quantopian/pyfolio/commit/30bc21f47d4d8d59ad07af3c7b63de8a49e2057b

**Comment by twiecki** [comment]
Looks neat!

**Comment by justinlent** [comment]
PR open here:  https://github.com/quantopian/pyfolio/tree/vol_weight_port

One thing I just realized after adding the portfolio returns functions to accomplish this to timeseries.py was that perhaps we want to breakout all portfolio returns construction functions into a new library file like portfolio.py

Let me know your thoughts @twiecki

**Comment by justinlent** [comment]
Closed with https://github.com/quantopian/pyfolio/commit/3c45d9e780f93fbdc7c2236e1fd66ab8529a6897
