### ISSUE TITLE
test_drawdown_overlaps failing on master

### ISSUE THREAD

**Issue by richafrank** [quantopian/pyfolio#649]
I fixed the flake8 failure that was masking this, but Travis CI (and local) nosetests runs are still failing with:
```
FAIL: test_drawdown_overlaps (pyfolio.tests.test_timeseries.TestDrawdown)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/quantopian/pyfolio/pyfolio/tests/test_timeseries.py", line 186, in test_drawdown_overlaps

    self.assertLessEqual(recovery, peak)

AssertionError: NaT not less than or equal to NaT
```
Looks to have started with https://github.com/quantopian/pyfolio/pull/634. cc @twiecki @Ildhesten

**Comment by Ildhesten** [comment]
Hi @richafrank,

I noticed that when I committed my last changes. I made a subsequent PR #635 that should address this issue.

However it was never merged into master. Maybe @twiecki can merge them in after reviewing.

**Comment by Ildhesten** [comment]
As I recall the issue with the test in its original form is when a value of NaT is passed, which has NaN like behaviour that  means it will never be equal to it self. The recommended way of testing for NaT seems to be pd.isnull, so that is why I changed the condition to that, and now the test passes.

**Comment by richafrank** [comment]
Ah thanks so much @Ildhesten ! Sorry I didn't look for that PR earlier. 

The PR makes sense to me, though it needs rebasing now. We can see if @twiecki wants to chime in as well...

**Comment by twiecki** [comment]
Looks good to me, thanks!
