### ISSUE TITLE
annual_returns incorrect in calendar mode

### ISSUE THREAD

**Issue by ACampbell22** [quantopian/pyfolio#65]
```
if style == 'calendar':
        num_years = len(returns) / 252
        df_cum_rets = cum_returns(returns, starting_value=100)
        start_value = df_cum_rets[0]
        end_value = df_cum_rets[-1]
        return ((end_value - start_value) / start_value) / num_years
```

Because the 252 is an integer, this function will return an inf for all return series shorter than one year.

Just gotta change the 252 to a float.

**Comment by ssanderson** [comment]
This isn't actually true.  On line https://github.com/quantopian/pyfolio/pull/66/files#diff-dd656075c4a67ac1cd34b18065e18791L15 we do a `from __future__ import division`, which gives integer division the same semantics as floating point division.

**Comment by twiecki** [comment]
I think this happened semi-simultaneously.
