### ISSUE TITLE
We should use a .rst file for the README and use it for our PyPI long description

### ISSUE THREAD

**Issue by ssanderson** [quantopian/pyfolio#72]
GitHub can render .rst perfectly well, and this makes the PyPI description much nicer.  

c.f. https://github.com/quantopian/pgcontents/blob/master/README.rst, https://pypi.python.org/pypi/pgcontents/

**Comment by twiecki** [comment]
I try to avoid mixing reST and markdown in the same project. Moreover, our documentation system, `mkdocs` requires markdown (http://quantopian.github.io/pyfolio/)  I also think few would go to pypi for documentation so a short two-sentence description is probably good enough.

**Comment by ssanderson** [comment]
@twiecki the long description isn't really meant to be documentation though, it's advertising.  If I google for something like "python risk visualization" and end up on our pyfolio page, it looks like it's basically unmaintained: https://pypi.python.org/pypi/pyfolio.  In zipline, we try to naively convert our markdown into rst, but that looks awful (https://pypi.python.org/pypi/zipline), and requires that we have pandoc installed when uploading to pypi.

At the very least, we should should have a proper .rst introduction inline in the setup.py.  My personal feeling is that the easiest, most maintainable, and most "pythonic" (for whatever that's worth) way to do this is to write our README in rst and read it into our setup.py.

**Comment by twiecki** [comment]
But then what would we do for the markdown file we need for http://quantopian.github.io/pyfolio/?

I do like your suggestiohn of having a .rst introduction for pyfolio in setup.py.
