### ISSUE TITLE
Remove live_algo_start date and replace with returns_out_of_sample

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#81]

**Comment by twiecki** [comment]
Actually this is a bit tricky I just realized because of positions and transactions which we assume to have the same length as the returns. So then we'd need to pass in positions_oos and transactions_oos as well which is a bit cumbersome. So maybe stick with the `live_start_date` which defaults to None?

**Comment by gusgordon** [comment]
Oh, right. I think this is fine for now then. In the future, if we decide we want to accept multiple dfs for oos, then that can just lie on top of what we will have, we would simply retain the optional live_start_date which is a useful feature anyway.

Then this issue now becomes just turning things off when no date is passed.

**Comment by twiecki** [comment]
Yep!
