### ISSUE TITLE
[BUG] backtest object does not have a gross_leverage field

### ISSUE THREAD

**Issue by humdings** [quantopian/pyfolio#85]
`pyfolio.utils.extract_rets_pos_txn_from_backtest_obj` does not work because Backtest.daily_performance does not have a 'gross_leverge' field.

**Comment by humdings** [comment]
This should be fixed once the pyfolio stuff is added to research.

**Comment by twiecki** [comment]
Isn't this obsolete with https://github.com/quantopian/pyfolio/pull/87 merged?

**Comment by humdings** [comment]
Yup, closing
