### ISSUE TITLE
test_calc_multifactor only uses a single factor

### ISSUE THREAD

**Issue by humdings** [quantopian/pyfolio#89]
`test_calc_multifactor` and `test_multifactor_beta` only have a single factor passed to them. These tests should be made more robust. Anybody opposed to keeping a small csv of test data, or we can use random data with a fixed seed, thoughts?

**Comment by gusgordon** [comment]
It's a good idea, but I think these functions should get deprecated in the future in favor of having some flexible beta calculation function.

**Comment by humdings** [comment]
Sounds good, I think this PR is a step towards better regression methods but we will still need better tests either way. 
https://github.com/quantopian/pyfolio/pull/63
