### ISSUE TITLE
get_symbol_rets should accept start and end times and only update cache if necessary

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#95]
Here's an idea:

@humdings already made the suggestion of adding start and end dates as keyword arguments to `get_symbol_rets` which I think is a good idea. Then once we have that and SPY gets requested, we could check if the end_date is later than what we have cached and only update the cache if necessary. Now we are updating if it's older than a day which is unnecessary and causes daily re-downloading of SPY which can take a while.

Thoughts?

**Comment by gusgordon** [comment]
Yeah, good idea, this is the correct way to handle it.

To tack on here, @ssanderson and I talked a little more about whether or not to force users to have to explicitly call the benchmark. So for example, it would be:
`create_full_tear_sheet(returns, benchmark_returns=get_symbol_rets('SPY'))`

I don't think this is too harmful to ease of use, but IMO still not worth it. I think the best solution is to have a warning or something whenever we are downloading data. See https://github.com/quantopian/pyfolio/pull/91. There are definitely a few nontrivial things we should do with this function.
